<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="sk" xml:lang="sk"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Úvod do lineárnej regresie – Pravdepodobnosť a štatistika 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./report.html" rel="next">
<link href="./ttest.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Žiadne výsledky",
    "search-matching-documents-text": "zhodné dokumenty",
    "search-copy-link-title": "Skopírovať odkaz pre vyhľadávanie",
    "search-hide-matches-text": "Skryť ďalšie výsledky",
    "search-more-match-text": "ďalší výsledok v tomto dokumente",
    "search-more-matches-text": "ďalších výsledkov v tomto dokumente",
    "search-clear-button-title": "Vymazať",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Zrušiť",
    "search-submit-button-title": "Odoslať",
    "search-label": "Hľadať"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Prepnúť postrannú navigáciu" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./reg.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Úvod do lineárnej regresie</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Prepnúť postrannú navigáciu" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Hľadať" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Pravdepodobnosť a štatistika 2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Hľadať"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O tomto kurze</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Úvod do jazyka R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Premenné a dátové štruktúry</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Náhodné čísla a simulácie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Čistenie dát</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Zopakovanie pojmov</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./depen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Náhodné vektory a súvis medzi náhodnými premennými</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Zobrazovanie dát</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Štatistické testovanie hypotéz</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Úvod do lineárnej regresie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Komunikácia výsledkov</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Obsah</h2>
   
  <ul>
  <li><a href="#lineárny-regresný-model" id="toc-lineárny-regresný-model" class="nav-link active" data-scroll-target="#lineárny-regresný-model"><span class="header-section-number">9.1</span> Lineárny regresný model</a></li>
  <li><a href="#maticová-notácia" id="toc-maticová-notácia" class="nav-link" data-scroll-target="#maticová-notácia"><span class="header-section-number">9.2</span> Maticová notácia</a></li>
  <li><a href="#názvoslovie" id="toc-názvoslovie" class="nav-link" data-scroll-target="#názvoslovie"><span class="header-section-number">9.3</span> Názvoslovie</a></li>
  <li><a href="#ako-na-to" id="toc-ako-na-to" class="nav-link" data-scroll-target="#ako-na-to"><span class="header-section-number">9.4</span> Ako na to</a></li>
  <li><a href="#geometria-najmenších-štvorcov" id="toc-geometria-najmenších-štvorcov" class="nav-link" data-scroll-target="#geometria-najmenších-štvorcov"><span class="header-section-number">9.5</span> Geometria najmenších štvorcov</a></li>
  <li><a href="#konfidenčné-intervaly" id="toc-konfidenčné-intervaly" class="nav-link" data-scroll-target="#konfidenčné-intervaly"><span class="header-section-number">9.6</span> Konfidenčné intervaly</a></li>
  <li><a href="#viacrozmerná-lineárna-regresia" id="toc-viacrozmerná-lineárna-regresia" class="nav-link" data-scroll-target="#viacrozmerná-lineárna-regresia"><span class="header-section-number">9.7</span> Viacrozmerná lineárna regresia</a></li>
  <li><a href="#nelineárne-vzťahy-a-lineárna-regresia" id="toc-nelineárne-vzťahy-a-lineárna-regresia" class="nav-link" data-scroll-target="#nelineárne-vzťahy-a-lineárna-regresia"><span class="header-section-number">9.8</span> Nelineárne vzťahy a lineárna regresia</a></li>
  <li><a href="#testovanie-podmodelov" id="toc-testovanie-podmodelov" class="nav-link" data-scroll-target="#testovanie-podmodelov"><span class="header-section-number">9.9</span> Testovanie podmodelov</a></li>
  <li><a href="#transformácie-a-interpretácia" id="toc-transformácie-a-interpretácia" class="nav-link" data-scroll-target="#transformácie-a-interpretácia"><span class="header-section-number">9.10</span> Transformácie a interpretácia</a>
  <ul class="collapse">
  <li><a href="#level-level-model" id="toc-level-level-model" class="nav-link" data-scroll-target="#level-level-model"><span class="header-section-number">9.10.1</span> Level-level model</a></li>
  <li><a href="#log-level-model" id="toc-log-level-model" class="nav-link" data-scroll-target="#log-level-model"><span class="header-section-number">9.10.2</span> Log-level model</a></li>
  <li><a href="#level-log-model" id="toc-level-log-model" class="nav-link" data-scroll-target="#level-log-model"><span class="header-section-number">9.10.3</span> Level-log model</a></li>
  <li><a href="#log-log-model" id="toc-log-log-model" class="nav-link" data-scroll-target="#log-log-model"><span class="header-section-number">9.10.4</span> Log-log model</a></li>
  </ul></li>
  <li><a href="#zhrnutie" id="toc-zhrnutie" class="nav-link" data-scroll-target="#zhrnutie"><span class="header-section-number">9.11</span> Zhrnutie</a></li>
  <li><a href="#cvičenia" id="toc-cvičenia" class="nav-link" data-scroll-target="#cvičenia"><span class="header-section-number">9.12</span> Cvičenia</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="reg" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Úvod do lineárnej regresie</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Doteraz sme sa naučili načítať dataset, zobraziť dáta, vypočítať a zobraziť korelácie a otestovať či je medzi nejakými skupinami významný rozdiel. Teraz sa budeme viacej venovať <strong>súvzťažnosti</strong> rôznych premenných.</p>
<p>Začnime príkladom. Majme informácie o tom, koľko hodín sa študenti pripravujú na test a ich výsledku na teste.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pozorujeme pozitívnu závislosť, čo nie je prekvapivé. Miera ich lineárnej súvzťažnosti, teda korelácia, je rovná <span class="math inline">\(91.8\%\)</span>, takže veľmi vysoká.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9177971</code></pre>
</div>
</div>
<p>Možno by sme chceli nejakým spôsobom popísať, ako presne rastie výsledok testu s úsilím, meraným počtom hodín strávených štúdiom, kvantifikovať túto závislosť.</p>
<p>Uvažujme situáciu, že absolútne nepripravený študent uhádne <span class="math inline">\(40\%\)</span> a potom každá strávená hodina učenia mu zvýši očakávaný výsledok o 1 percentuálny bod.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Nie je to úplne nemysliteľné ale keď sa zahľadím na dáta spolu s touto modrou čiarou, tak vidíme, že fituje len nedobre. Ak by sme si mysleli, že nepripravený študent uhádne 50% na teste a každá hodina štúdia navýši očakávaný výsledok o 0.8 percentuálneho bodu, potom by to vyzeralo nasledovne:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Táto priamka oveľa lepšie fituje dáta. Avšak asi by sme potrebovali nejaký systematickejší spôsob ako zvoliť tú priamku, ktorá najlepšie fituje dáta. Slovo “najlepšie” implikuje, že potrebujeme mať <strong>merateľné kritérium</strong>, ktoré bude posudzovať kvalitu fitu. Jedným takýmto kritériom je napríklad suma štovrcov vertikálnych vzdialeností.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hoursLearned, testScore)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>lmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(testScore <span class="sc">~</span> hoursLearned)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(lmod)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> lmod<span class="sc">$</span>coeff</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>predictedScore <span class="ot">&lt;-</span> beta[<span class="dv">1</span>] <span class="sc">+</span> beta[<span class="dv">2</span>]<span class="sc">*</span>hoursLearned</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(hoursLearned, predictedScore)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(hoursLearned, predictedScore,hoursLearned,testScore)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(hoursLearned, predictedScore, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Spomedzi všetkých možných priamiek, je práve táto ktorá minimializuje sumu štvorcov vertikálnych výchyliek. Budeme používať nasledovné značenie:</p>
<ul>
<li><span class="math inline">\(n\)</span> je veľkosť dátovej vzorky (u nás <span class="math inline">\(n=10\)</span>)</li>
<li><span class="math inline">\(i \in \{1,2,\dots,n \}\)</span> bude index pozorovania (u nás <span class="math inline">\(i\)</span> bude označovať jedného z 10 študentov)</li>
<li><span class="math inline">\(x_i\)</span> bude označovať nezávislú premennú pre pozorovanie <span class="math inline">\(i\)</span> (koľko hodín sa učil <span class="math inline">\(i\)</span>-ty śtudent)</li>
<li><span class="math inline">\(y_i\)</span> bude označovať závislú premennú pre pozorovanie <span class="math inline">\(i\)</span> (výsledok testu <span class="math inline">\(i\)</span>-teho śtudenta)</li>
</ul>
<p>Nájdenie najlepšej priamky v zmysle vedie na takýto optimializačný problém. <span class="math display">\[(\hat \beta_0, \hat \beta_1) = \arg \min_{(\beta_0, \beta_1)} \sum_{i=1}^{n} \Big(y_i - (\beta_0 + \beta_1 x_i) \Big)^2.\]</span> Na výpočet sme použili funkciu <code>lm</code> a naše odhady <span class="math inline">\((\hat \beta_0, \hat \beta_1)\)</span> neznámych parametrov <span class="math inline">\((\beta_0, \beta_1)\)</span> sú <span class="math inline">\(46.52\)</span> a <span class="math inline">\(1.12.\)</span> Číslo <span class="math inline">\(46.52\)</span> je výška v ktorej pretína čierna priamka os y a číslo <span class="math inline">\(1.12\)</span> je smernica tejto priamky, teda ako rýchlo rastie.</p>
<p>Ešte predtým, ako sa zavŕtame do detailov, uvedomme si nasledovné skutočnosti</p>
<ul>
<li>Chyba je symetrická - penalizujeme podhodnotenie aj nadhodnotenie rovnako.</li>
<li>Chyba rastie veľmi rýchlo - štvorec, teda kvadratická funkcia, rastie veľmi rýchlo a preto sa budeme snažiť vyhýbať veľmi veľkým chybám.</li>
<li>Chyby sú merané ako vertikálne vzdialenosti. Takže ak vymeníme úlohy <span class="math inline">\(x\)</span> a <span class="math inline">\(y\)</span>, tak naše výsledky sa <strong>zmenia</strong>.</li>
</ul>
<p>Parametre minimalizujúce sumu štvorcov (a teda maximalizujú fit) sa v tomto prípade dajú spočítať aj analyticky - teda existuje explicitný vzťah do ktorého dosadíme hodnoty <span class="math inline">\(x_i, y_i\)</span> a rovno priamo dostaneme <span class="math inline">\((\hat \beta_0, \hat \beta_1).\)</span> Toto je užitočné lebo sa ani nemusíme spoliehať na numerické algoritmy.</p>
<p>Vzťah pre <span class="math inline">\((\hat \beta_0, \hat \beta_1)\)</span> vyzerá nasledovne:</p>
<p><span class="math display">\[\hat \beta_1 = \frac{\sum_{i=1}^n (y_i-\bar{y})(x_i - \bar{x}) }{\sum_{i=1}^n (x_i-\bar{x})^2} \]</span></p>
<p><span class="math display">\[\hat \beta_0 = \bar y - \hat \beta_1 \bar x.\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_points.png" style="width:49.0%;height:20.0%" class="figure-img"></p>
<figcaption>Rôzne fitované priamky.</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_badfit1.png" style="width:49.0%;height:20.0%" class="figure-img"></p>
<figcaption>Rôzne fitované priamky.</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_badfit2.png" style="width:49.0%;height:20.0%" class="figure-img"></p>
<figcaption>Rôzne fitované priamky.</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_squ.png" style="width:49.0%;height:20.0%" class="figure-img"></p>
<figcaption>Rôzne fitované priamky.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_squ_col.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Ilustrácia metódy najmenších štvorcov</figcaption>
</figure>
</div>
</div>
</div>
<section id="lineárny-regresný-model" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="lineárny-regresný-model"><span class="header-section-number">9.1</span> Lineárny regresný model</h2>
<p>Môžeme sa na problém pozrieť nasledovne. Predpokladajme, že skutočné <span class="math inline">\(y_i\)</span> a <span class="math inline">\(x_i\)</span> sú v nasledujúcom vzťahu</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon_i,\]</span> kde <span class="math inline">\(\epsilon_i\)</span> označuje aproximačnú chybu. Takto rozdelíme variabilitu v <span class="math inline">\(y_i\)</span> na systematickú časť (<span class="math inline">\(\beta_0 + \beta_1 x_i\)</span>) a nesystematickú časť (<span class="math inline">\(\epsilon_i\)</span>). Pomocou nášho odhadu <span class="math inline">\((\hat \beta_0, \hat \beta_1)\)</span> neznámych parametrov <span class="math inline">\((\beta_0, \beta_1)\)</span> teda dostávame <strong>odhad</strong> <span class="math inline">\(\hat \epsilon_i = y_i - (\hat \beta_0 + \hat \beta_1 x_i)\)</span> skutočných aproximačných chýb <span class="math inline">\(\epsilon_i\)</span>, ktoré sú nepozorované.</p>
<p>Toto je samozrejme nejaké zjednodušenie. Nemusíme veriť, že je to <em>presne</em> tak, robíme to preto, aby sme systematizovali kvantifikáciu vzťahu medzi dvomi veličinami. Ak predpokláme o chybách, že sú rozdelené normálne</p>
<p><span class="math display">\[\epsilon_i \sim N(0, \sigma^2),\]</span> tak potom vieme odvodiť aj pravdepodobnostné správanie samotných odhadov <span class="math inline">\((\hat \beta_0, \hat \beta_1),\)</span> ktoré majú taktiež normálne rozdelenie a sú centrované okolo skutočných hodnôt <span class="math inline">\((\beta_0,\beta_1).\)</span></p>
</section>
<section id="maticová-notácia" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="maticová-notácia"><span class="header-section-number">9.2</span> Maticová notácia</h2>
<p>Ak rovnice <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span> napíšeme pod seba <span class="math inline">\(i = 1,2,\dots,n,\)</span> dostaneme</p>
<p><span class="math display">\[ \begin{pmatrix}y_1 \\ y_2 \\ \vdots \\ y_n \end{pmatrix} = \begin{pmatrix}1 &amp; x_1 \\1 &amp; x_2 \\ \vdots&amp; \vdots \\ 1 &amp; x_n \end{pmatrix} \begin{pmatrix}\beta_0 \\ \beta_1 \end{pmatrix} + \begin{pmatrix}\epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{pmatrix}\]</span> alebo skrátene len <span class="math display">\[y = X\beta + \epsilon.\]</span></p>
<p>Odhad minimalizujúci súčet štvorcov odchýlok je v maticovom zápise nasledovný:</p>
<p><span class="math display">\[\hat \beta = (X^T X)^{-1} X^T y\]</span></p>
<p>Ak uvažujeme, že <span class="math inline">\(\epsilon_i \sim N(0, \sigma^2)\)</span> potom <span class="math inline">\(\epsilon \sim N(0, \sigma^2I_n),\)</span> kde <span class="math inline">\(I_n\)</span> označuje <span class="math inline">\(n \times n\)</span> maticu identity (diagonálnu maticu s jednotkami na diagonále a nulami inde).</p>
<span class="math display">\[\begin{eqnarray*}
\hat \beta &amp;=&amp; (X^T X)^{-1} X^T y \\
&amp;=&amp; (X^T X)^{-1} X^T (X\beta + \epsilon) \\
&amp;=&amp; \beta + (X^T X)^{-1} X^T\epsilon
\end{eqnarray*}\]</span>
<p>Preto</p>
<span class="math display">\[\begin{eqnarray*}
\hat \beta &amp;\sim&amp; N(\beta, (X^T X)^{-1} X^T Var[\epsilon] X (X^T X)^{-1}  )\\
        &amp;\sim&amp; N(\beta, (X^T X)^{-1} X^T \sigma^2I_n X (X^T X)^{-1}  )\\
        &amp;\sim&amp; N(\beta, \sigma^2 (X^T X)^{-1} X^T X (X^T X)^{-1}  )\\
        &amp;\sim&amp; N(\beta, \sigma^2 (X^T X)^{-1}).
\end{eqnarray*}\]</span>
<p>Teda my úplne presne vieme aké má pravdepodobnostné rozdelenie. Až na varianciu chýb <span class="math inline">\(\sigma^2\)</span>. Tú nevieme a znova len budeme musieť odhadnúť. Dobrým odhadom (nevychýleným) je</p>
<p><span class="math display">\[\hat \sigma^2 = \sum_{i=1}^n  \frac{\hat \epsilon_i^2}{n-k} = \sum_{i=1}^n  \frac{ \left(y_i - (\beta_0 + \beta_1 x_i)\right)^2}{n-k},\]</span> kde <span class="math inline">\(k\)</span> je počet parametrov v modeli (v našom prípade 2).</p>
<p>Tento odhad variancie chýb použijeme na odhad kovariančnej matice <span class="math inline">\(\hat \beta\)</span>:</p>
<p><span class="math display">\[\hat Var[\hat \beta] = \hat Var\left[\begin{pmatrix}\hat \beta_0 \\ \hat \beta_1 \end{pmatrix}\right] = \hat \sigma^2 (X^T X)^{-1}.\]</span> Diagonálne elementy <span class="math inline">\(2 \times 2\)</span> matice <span class="math inline">\(Var[\hat \beta]\)</span> sú <span class="math inline">\(Var\left[\hat \beta_0\right]\)</span> a <span class="math inline">\(Var\left[\hat \beta_1\right].\)</span> Podobne diagonálne členy odhadu (symetrickej) matice <span class="math inline">\(\hat Var [\hat \beta]\)</span> sú <span class="math inline">\(\hat Var\left[\hat \beta_0\right]\)</span> a <span class="math inline">\(\hat Var\left[\hat \beta_1\right]\)</span>, mimo diagonály sú <span class="math inline">\(\hat Cov\left[\hat \beta_0,\hat \beta_1\right]\)</span>.</p>
</section>
<section id="názvoslovie" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="názvoslovie"><span class="header-section-number">9.3</span> Názvoslovie</h2>
<p>Pripomeňme si, čo je čo. V matematike je pekným zvykom rozumieť, čo ktoré objekty označujú.</p>
<ul>
<li><span class="math inline">\(x_4\)</span> je náhodná premenná, ide o náhodnú premennú <span class="math inline">\(x\)</span> nameranú pre štvrté pozorovanie,</li>
<li><span class="math inline">\(y_7\)</span> je náhodná premenná, ide o náhodnú premennú <span class="math inline">\(y\)</span> nameranú pre siedme pozorovanie,</li>
<li><span class="math inline">\(\epsilon_2\)</span> je náhodná premenná, realizáciu tejto náhodnej premennej druhéhp pozorovania nepozorujeme,</li>
<li><span class="math inline">\(\bar x\)</span> je náhodná premenná (lebo je to funkcia iných náhodných premenných),</li>
<li><span class="math inline">\(\bar y\)</span> je náhodná premenná (lebo je to funkcia iných náhodných premenných),</li>
<li><span class="math inline">\(\beta_0\)</span> je číslo. Fixné ale nám neznáme. Hovorí o priesečníku (s osou <span class="math inline">\(y\)</span>) neznámej ale fixnej priamky <span class="math inline">\(\beta_0 + \beta_1 x\)</span>,</li>
<li><span class="math inline">\(\hat \beta_0\)</span> je náhodná premenná. Je funkciou iných náhodných premenných a odhaduje nám neznáme číslo <span class="math inline">\(\beta_0\)</span>,</li>
<li><span class="math inline">\(\beta_1\)</span> je číslo. Fixné ale nám neznáme. Hovorí o smernici neznámej ale fixnej priamky <span class="math inline">\(\beta_0 + \beta_1 x\)</span>,</li>
<li><span class="math inline">\(\hat \beta_1\)</span> je náhodná premenná. Je funkciou iných náhodných premenných a odhaduje nám neznáme číslo <span class="math inline">\(\beta_1\)</span>,</li>
<li><span class="math inline">\(y\)</span> je vektor náhodných premenných,</li>
<li><span class="math inline">\(X\)</span> je matica náhodných premenných, ktorá sa skladá z dvoch stĺpcov: jednotiek a vektora náhodných premenných <span class="math inline">\(x_1\)</span> až <span class="math inline">\(x_n\)</span>,</li>
<li><span class="math inline">\(\beta\)</span> je fixný ale nám neznámy <span class="math inline">\(2 \times 1\)</span> vektor,</li>
<li><span class="math inline">\(\hat \beta\)</span> je náhodný vektor,</li>
<li><span class="math inline">\(\sigma^2\)</span> je fixné ale nám neznáme číslo. Je to variancia chýb <span class="math inline">\(\epsilon_i\)</span>. Uvažujeme, že sú rovnaké pre všetky <span class="math inline">\(i=1,\dots,n,\)</span></li>
<li><span class="math inline">\(\hat \sigma^2\)</span> je náhodná premenná. Je to odhad nám neznámej hodnoty <span class="math inline">\(\sigma^2\)</span>,</li>
<li><span class="math inline">\(Var\left[\hat \beta\right] = \sigma^2 (X^T X)^{-1}\)</span> je kovariančná matica náhodného vektora <span class="math inline">\(\hat \beta\)</span>,</li>
<li><span class="math inline">\(\hat Var\left[\hat \beta\right] = \hat \sigma^2 (X^T X)^{-1}\)</span> je odhad kovariančnej matice náhodného vektora <span class="math inline">\(\hat \beta\)</span>.</li>
</ul>
</section>
<section id="ako-na-to" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="ako-na-to"><span class="header-section-number">9.4</span> Ako na to</h2>
<p>Čiaru minimalizujúcu fit v zmysle najmenších štvorcov odchýlok dostaneme aj použitím funkcie <code>geom_smooth</code> možnosťou <code>method="lm"</code> a <code>formula = "y~x"</code> ako je uvedené nižšie.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">hours =</span> hoursLearned, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">score =</span> testScore)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>df, <span class="fu">aes</span>(<span class="at">x=</span>hours,<span class="at">y=</span>score)) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">"y~x"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">se=</span><span class="cn">FALSE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ak chceme detailné informácie o krivke, použijeme funkciu <code>lm</code> a <code>summary</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(testScore <span class="sc">~</span> hoursLearned)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = testScore ~ hoursLearned)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.2990  -2.2503  -0.8337   1.9847  12.0375 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   46.5193     3.6968  12.584 1.49e-06 ***
hoursLearned   1.1195     0.1712   6.538 0.000181 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.246 on 8 degrees of freedom
Multiple R-squared:  0.8424,    Adjusted R-squared:  0.8226 
F-statistic: 42.75 on 1 and 8 DF,  p-value: 0.0001807</code></pre>
</div>
</div>
<p>Je tu veľa informácií. Všetky tieto čísla si dopodrobna rozoberieme.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Regresná tabuľka</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>Parameter formula nám hovorí akou rovnicou aproximujeme <span class="math inline">\(y_i\)</span> pomocou <span class="math inline">\(x_i\)</span>.</li>
<li>Residuals označujú charakteristiky distribúcie odhadovaných chýb, takže hodnoty <span class="math inline">\(\hat \epsilon_i\)</span>.</li>
<li>V tabuľke koeficientov je prvý riadok o odhade <span class="math inline">\(\hat \beta_0\)</span> a druhý riadok o odhade <span class="math inline">\(\hat \beta_1\)</span>.</li>
<li>Prvý stĺpec sú samotné hodnoty odhadov, v druhom sú odhady smerodajných odchýlok odhadov, nazývané aj <strong>štandardné chyby</strong> (v angl. Standard errors).</li>
<li>V treťom stĺpci sú testovacie štatistiky, ktoré testujú hypotézu <span class="math inline">\(H_0: \beta_0 = 0\)</span> a <span class="math inline">\(H_0: \beta_1 = 0\)</span> a v poslednom stĺpci sú príslušné p-hodnoty týchto testov. Testovacia štatistika má formu: <span class="math display">\[T=\frac{\hat \beta_1}{\hat{sd}(\hat \beta_1)}\]</span> a má <a href="https://lukaslaffers.github.io/pas1/snp.html#studentovo-rozdelenie-t-rozdelenie">Studentovo t-rozdelenie</a>, s <span class="math inline">\(n-p\)</span> stupňami voľnosti, kde <span class="math inline">\(p\)</span> je počet odhadnutých parametrov (v jednoduchej lineárnej regresie sú to dva parametre, ktoré odhadujeme: <span class="math inline">\(\beta_0\)</span> a <span class="math inline">\(\beta_1\)</span>). V menovateli je <span class="math inline">\(\hat{sd}(\hat \beta_1)\)</span>, čo je odhad smerodajnej odchýlky odhadu <span class="math inline">\(\hat \beta_1,\)</span> teda <span class="math inline">\(\hat{sd}(\hat \beta_1) = \sqrt{\hat Var \left[\hat \beta_1 \right]}.\)</span> Táto kvantita sa tiež označuje ako štandardná chyba (v anj. standard error). Všeobecný prístup k testovaniu je vysvetlený <a href="https://lukaslaffers.github.io/pas2/reg.html#testovanie-podmodelov">neskôr</a>.</li>
</ul>
<p>Pokračujeme ďalej:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Regresná tabuľka</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>V tabuľke máme aj reziduálnu štandardnú chybu, čo je odhad smerodajnej odchýlky reziduí <span class="math inline">\(\hat{sd}[\hat \epsilon]\)</span>,</li>
<li>Počet <strong>stupňov voľnosti</strong> je počet pozorovaní mínus počet parametrov v modeli,</li>
<li><span class="math inline">\(R^2\)</span> je číslo medzi 0 a 1, ktoré vyjadruje kvalitu fitu. Hodnota 0 znamená, že <span class="math inline">\(x\)</span> neposkytuje žiadnu užitočnú informáciu na fitovanie <span class="math inline">\(y\)</span> (pomocou lineárneho modelu), hodnota 1 znamená, že <span class="math inline">\(x\)</span> perfektne predikuje <span class="math inline">\(y\)</span> (pomocou lineárneho modelu),</li>
<li>F štatistika testuje významnosť regresie, teda v tomto prípade porovnáva modely <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i,\)</span> a <span class="math inline">\(y_i = \beta_0 + \epsilon_i,\)</span> takže v tomto prípade testuje <span class="math inline">\(H_0: \beta_1 = 0.\)</span> (Všimnime si, že p-hodnota je rovnaká ako v riadku pri <span class="math inline">\(\hat \beta_1\)</span>, až na zaokrúhlenie).</li>
</ul>
</section>
<section id="geometria-najmenších-štvorcov" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="geometria-najmenších-štvorcov"><span class="header-section-number">9.5</span> Geometria najmenších štvorcov</h2>
<p>Metóda, ktorá nastavuje parametre neznámej priamky tak, že minimalizuje sumu štvorcov má zaujimavú geometrickú interpretáciu.</p>
<p>Ide totiž o projekciu.</p>
<p>&nbsp;</p>
<p>Snažíme sa projektovať vektor <span class="math inline">\(y = (y_1, y_2, \dots, y_n)^T\)</span> do podpriestoru generovaného konštantných jednotiek <span class="math inline">\((1,1,\cdots,1)^T\)</span> a <span class="math inline">\(x = (x_1, x_2, \dots, x_n)^T\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_geom2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Geometria najmenších štvorcov</figcaption>
</figure>
</div>
</div>
</div>
<p>Obrázok ukazuje geometriu najmenších štvorcov. Každý vektor (šípka) reprezentuje bod v n-rozmernom priestore. Vektor <span class="math inline">\(y\)</span> sa nenachádza v priestore generovanom vektorom konštantných jednotiek a <span class="math inline">\(x\)</span>. Metóda najmenších štvorcov projektu vektor <span class="math inline">\(y\)</span> do tohoto podpriestoru, teda hľadá minimálnu vzdialenosť červeného vektora <span class="math inline">\(\hat \epsilon\)</span> v zmysle euklidovskej vzdialenosti (to je taká tá obyčajná na akú sme zvyknú v našom 3D svete a meriame ju pravítkom). Takže tu máme viacerozmernú verziu Pytagorovho trojuholníka.</p>
<p>V obrázku máme znázornené dva rozklady <span class="math inline">\(n-\)</span>rozmerného vektora <span class="math inline">\(y = (y_1, \cdots, y_n)^T.\)</span></p>
<p>Prvý <span class="math display">\[ y = {\color{blue}\hat y} + {\color{red}\hat \epsilon}\]</span> alebo vektorovo</p>
<p><span class="math display">\[
\begin{pmatrix}
y_1 \\ y_2 \\ \vdots \\ y_n
\end{pmatrix}
=
{\color{blue}
\begin{pmatrix}
1 &amp; x_1 \\
1 &amp; x_2 \\
\vdots &amp; \vdots \\
1 &amp; x_n
\end{pmatrix}
\begin{pmatrix}
\hat \beta_0 \\ \hat \beta_1
\end{pmatrix}}
+
{\color{red}
\begin{pmatrix}
\hat \epsilon_1 \\ \hat \epsilon_2 \\ \vdots \\ \hat \epsilon_n
\end{pmatrix}} =
{\color{blue}
\begin{pmatrix}
\hat y_1 \\ \hat y_2 \\ \vdots \\ \hat y_n
\end{pmatrix}}
+
{\color{red}
\begin{pmatrix}
\hat \epsilon_1 \\ \hat \epsilon_2 \\ \vdots \\ \hat \epsilon_n
\end{pmatrix}}
\]</span></p>
<p>je výsledkom odhadovania pôvodného modelu: <span class="math inline">\(y_i = {\color{blue}\beta_0 + \beta_1 x_i} + {\color{red}\epsilon_i}.\)</span></p>
<p>Druhý <span class="math display">\[ y = {\color{green}\bar y} + {\color{orange}\bar \epsilon}\]</span> alebo vektorovo <span class="math display">\[
\begin{pmatrix}
y_1 \\ y_2 \\ \vdots \\ y_n
\end{pmatrix}
=
{\color{green}
\begin{pmatrix}
1  \\
1  \\
\vdots \\
1
\end{pmatrix}
\bar \beta_0
}
+
{\color{orange}
\begin{pmatrix}
\bar \epsilon_1 \\ \bar \epsilon_2 \\ \vdots \\ \bar \epsilon_n
\end{pmatrix}} =
{\color{green}
\begin{pmatrix}
1 \\  1 \\ \vdots \\  1
\end{pmatrix}
\bar y_n}
+
{\color{orange}
\begin{pmatrix}
\bar \epsilon_1 \\ \bar \epsilon_2 \\ \vdots \\ \bar \epsilon_n
\end{pmatrix}}
\]</span></p>
<p>je výsledkom odhadovania zjednodušeného modelu bez vysvetľujúcej premennej <span class="math inline">\(x\)</span>: <span class="math inline">\(y_i = {\color{green}\beta_0 } + {\color{orange} \bar \epsilon_i}.\)</span> Tento pesimistický model nedáva žiadnu šancu premennej <span class="math inline">\(x\)</span> aby vysvetlila variabilitu v premennej <span class="math inline">\(y.\)</span> Je to však užitočný rámec na porovnávanie.</p>
<p>Označme <span class="math inline">\(\mathbf{1}= (1,1,\cdots,1)^T = \begin{pmatrix}
1 \\ 1 \\ \vdots \\ 1
\end{pmatrix}\)</span> ako <span class="math inline">\(n-\)</span>rozmerný vektor jednotiek.</p>
<p>Vyššie sme využili <span class="math inline">\(\bar \beta_0 = \bar y_n\)</span> nakoľko: <span class="math display">\[{\color{green}\bar \beta_0} = (\mathbf{1} ^T \mathbf{1})^{-1} \mathbf{1} ^T y = \frac{1}{n}\mathbf{1} ^T y = \frac{\sum_{i=1}^n y_i}{n} = \bar y_n,\]</span> takže ide o jednoduchý aritmetický priemer. Rovnako <span class="math inline">\({\color{green}\bar y} = \mathbf{1} \bar y_n\)</span> označuje konštantný <span class="math inline">\(n-\)</span>rozmerný vektor aritmetických priemerov.</p>
<p>Miera (lineárneho) fitu je daná nasledovnou dekompozíciou</p>
<p><span class="math display">\[
{\color{orange}
\begin{pmatrix}
\bar \epsilon_1 \\ \bar \epsilon_2 \\ \vdots \\ \bar \epsilon_n
\end{pmatrix}} =
\begin{pmatrix}
y_1 - {\color{green}\bar y_n} \\ y_2 - {\color{green}\bar y_n} \\ \vdots \\ y_n - {\color{green}\bar y_n}
\end{pmatrix} =
\begin{pmatrix}
{\color{blue}\hat y_1} - {\color{green}\bar y_n}\\ {\color{blue}\hat y_2} - {\color{green}\bar y_n} \\ \vdots \\ {\color{blue}\hat y_n} - {\color{green}\bar y_n}
\end{pmatrix}
+
{
\begin{pmatrix}
y_1 - {\color{blue}\hat y_1}\\ y_2 - {\color{blue}\hat y_2} \\ \vdots \\ y_n - {\color{blue}\hat y_n}
\end{pmatrix}
}
=
{\color{purple}
\begin{pmatrix}
{\color{purple}\hat y_1} - {\color{purple}\bar y_n}\\ {\color{purple}\hat y_2} - {\color{purple}\bar y_n} \\ \vdots \\ {\color{purple}\hat y_n} - {\color{purple}\bar y_n}
\end{pmatrix}}
+
{\color{red}
\begin{pmatrix}
{\color{red}\hat \epsilon_1} \\ {\color{red}\hat \epsilon_2} \\ \vdots \\ {\color{red}\hat \epsilon_n}
\end{pmatrix}}
\]</span></p>
<p>a je popísaná nasledujúcim vzťahom:</p>
<p><span class="math display">\[R^2 = 1- \frac{\sum (y_i - {\color{blue}\hat y_i} )^2}{\sum (y_i - {\color{green}\bar y_n})^2} = 1- \frac{{{\color{red}RSS}}}{{{\color{orange}TSS}}} =  \frac{{\color{purple}ESS}}{{{\color{orange}TSS}}} = \frac{\sum ({\color{blue}\hat y_i} - {\color{green}\bar y_n} )^2}{\sum (y_i - {\color{green}\bar y_n})^2},\]</span> kde používame nasledovné značenie</p>
<ul>
<li><span class="math inline">\({\color{red}RSS}\)</span> - reziduálna suma štvorcov (residual sum of squares),</li>
<li><span class="math inline">\({\color{purple}ESS}\)</span> - vysvetlená suma štvorcov (explained sum of squares),</li>
<li><span class="math inline">\({\color{orange}TSS}\)</span> - celková suma štvorcov (total sum of squares).</li>
</ul>
<p>Nejde v podstate o nič iné ako odhad lineárnej súvzťažnosti medzi <span class="math inline">\(y\)</span> a odhadovaných <span class="math inline">\(\hat y\)</span>: <span class="math display">\[R^2 = \left(\hat{cor}(\hat y, y)\right)^2 = \frac{\sum (\bar y - \hat y_i )^2}{\sum (y_i - \bar y_i)^2}.\]</span></p>
<p>Ak je zjednodušený model <span class="math inline">\(y_i = {\color{green}\beta_0 } + {\color{orange} \bar \epsilon_i}\)</span> podobne dobrý ako zložitejší model <span class="math inline">\(y_i = {\color{blue}\beta_0 + \beta_1 x_i} + {\color{red}\epsilon_i},\)</span> potom <span class="math inline">\(R^2\)</span> bude blízke nule. Premenná <span class="math inline">\(x\)</span> nám totiž nepomôže k vysvetľovaniu <span class="math inline">\(y.\)</span></p>
<p>Naviac, skutočná závislosť medzi <span class="math inline">\(x\)</span> a <span class="math inline">\(y\)</span> je <strong>presne</strong> lineárna (teda ak platí model bez akejkoľvek chyby!): <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i,\)</span> práve vtedy a len vtedy, keď je <span class="math inline">\(R^2 = 1\)</span>.</p>
<p>Hodnota <span class="math inline">\(R^2\)</span> nám teda hovorí o miere <strong>lineárnej</strong> súvzťažnosti medzi fitovanými hodnotami <span class="math inline">\(\hat y\)</span> a skutočnými hodnotami <span class="math inline">\(y\)</span>. Toto však môže byť matúce, ak medzi dvomi premennými nie je lineárny vzťah. (Tuto ide o menej zábavnú verziu <a href="https://lukaslaffers.github.io/pas1/cov.html#miera-závislosti">datasetov s dinosaurom</a>.)</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_R2.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Veľmi rôzne dáta vedú na rovnaké miery fitu <span class="math inline">\(R^2\)</span>. (Zdroj: Faraway, Julian J. Linear models with R. Chapman and Hall/CRC, 2004.)</figcaption>
</figure>
</div>
</div>
</div>
<p>Ale to je tak vždy, keď sa komplexnú informáciu snažím skomprimovať do jedného čísla, svet je totiž rozmanitý.</p>
</section>
<section id="konfidenčné-intervaly" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="konfidenčné-intervaly"><span class="header-section-number">9.6</span> Konfidenčné intervaly</h2>
<p>Chceli by sme kvantifikovať neistotu spojenú s odhadom budúcich hodnôt. Ako veľmi si môžeme byť istí tým, že študent učiaci sa 20 hodín bude mať očakávaný počet bodov práve <span class="math inline">\(\hat \beta_0 + \hat \beta_1 20 = 46.52 + 1.12 \cdot 20 = 68.92\)</span>?</p>
<p>Nakoľko vieme kvantifikovať neistotu spojenú s <span class="math inline">\(\hat \beta_0\)</span> a <span class="math inline">\(\hat \beta_1\)</span>, môžeme použiť na <span class="math inline">\(\hat \beta_0 + \hat \beta_1 x\)</span> pre akékoľvek číslo <span class="math inline">\(x\)</span>.</p>
<p>Stredná hodnota pre modelovanú premennú ak by <span class="math inline">\(x\)</span> nadobúdalo hodnotu <span class="math inline">\(x_0\)</span> je <span class="math display">\[\hat y_0 = \hat \beta_0 + \hat \beta_1 x_0 =  (1, x_0) \begin{pmatrix} \hat \beta_0 \\ \hat \beta_1 \end{pmatrix}\]</span></p>
<p>Zatiaľčo budúca hodnota je <span class="math display">\[y_0 = \hat y_0 + \epsilon_0\]</span></p>
<ul>
<li><span class="math inline">\(95\%\)</span>ný konfidenčný interval pre strednú hodnotu <span class="math inline">\(\hat y_0 \pm t_{n-p}^{(\alpha/2)} \hat \sigma \sqrt{ (1, x_0) (X^T X)^{-1}(1, x_0)^T}\)</span></li>
<li><span class="math inline">\(95\%\)</span>ný predičný interval pre budúcu hodnotu <span class="math inline">\(\hat y_0 \pm t_{n-p}^{(\alpha/2)} \hat \sigma \sqrt{1 + (1, x_0) (X^T X)^{-1}(1, x_0)^T}\)</span></li>
</ul>
<p>Ten druhý interval je širší, lebo v sebe zahŕňa aj informáciu o buducej chybe <span class="math inline">\(\epsilon_0\)</span></p>
<span class="math display">\[\begin{eqnarray*}
var(\hat y_0 + \epsilon_0) &amp;=&amp; var(\hat y_0)+ var(\epsilon_0) \\
&amp;=&amp;  (1, x_0) (X^T X)^{-1}(1, x_0)^T \sigma^2 + \sigma^2 \\
&amp;=&amp; \big({\color{green}1 +} (1, x_0) (X^T X)^{-1}(1, x_0)^T\big) \sigma^2
\end{eqnarray*}\]</span>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_ci.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Konfidenčné a predikčné intervaly.</figcaption>
</figure>
</div>
</div>
</div>
<p>Predikčné intervaly nie sú v <code>ggplot2</code> natívne, preto si ich musíme dorobiť mechanicky.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> hours, <span class="at">data=</span>df)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>pi95 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmod, <span class="at">interval=</span><span class="st">"prediction"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(lmod, interval = "prediction"): predictions on current data refer to _future_ responses</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df2      <span class="ot">&lt;-</span> <span class="fu">cbind</span>(df, pi95)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>df2, <span class="fu">aes</span>(<span class="at">x=</span>hours,<span class="at">y=</span>score)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> <span class="st">"y~x"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">se=</span><span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>lwr), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>upr), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="viacrozmerná-lineárna-regresia" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="viacrozmerná-lineárna-regresia"><span class="header-section-number">9.7</span> Viacrozmerná lineárna regresia</h2>
<p>Doteraz nám lineárna regresia slúžila na modelovanie vzťahu medzi dvomi veličinami. Častokrát však chceme použiť mnoho rôznych faktorov na predikovanie nejakej premennej. Napríklad</p>
<ul>
<li>rôzne vlastnosti ojazdeného auta môžu determinovať jeho trhovú cenu,</li>
<li>rôzne vlastnosti absolventa budú terminovať jeho mzdu o 10 rokov,</li>
<li>rôzne vlastnosti filmu môžu determinovať jeho obľúbenosť alebo zisk, ktorý vygeneruje.</li>
</ul>
<p>Začneme triviálnym rozšírením nášho modelu. Teraz nebudeme mať len jeden prediktor <span class="math inline">\(x\)</span> ale mnoho. Model bude vyzerať nasledovne:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \dots + \beta_p x_{ip} + \epsilon_{i}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_reg_linreg.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Vizualizácia lineárnej regresie, vľavo sa použitím len jednej vysvetľovacej premennej, vpravo dvomi. (Zdroj: Faraway, Julian J. Linear models with R. Chapman and Hall/CRC, 2004.)</figcaption>
</figure>
</div>
</div>
</div>
<p>Maticová notácia nám ostáva, len musíme predefinovať maticu <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[ \begin{pmatrix}y_1 \\ y_2 \\ \vdots \\ y_n \end{pmatrix} = \begin{pmatrix}1 &amp; x_{11} &amp; x_{12} &amp; \dots &amp; x_{1n} \\1 &amp; x_{21} &amp; x_{22} &amp; \dots &amp; x_{2n} \\ \vdots&amp; \vdots&amp; \vdots &amp; \vdots &amp; \vdots \\ 1 &amp; x_{n1} &amp; x_{n2} &amp; \dots &amp; x_{1n} \end{pmatrix} \begin{pmatrix}\beta_0 \\ \beta_1 \\ \beta_2\\ \vdots \\ \beta_p \end{pmatrix} + \begin{pmatrix}\epsilon_1 \\ \epsilon_2 \\ \vdots \\ \epsilon_n \end{pmatrix}\]</span> alebo skrátene len <span class="math display">\[y = X\beta + \epsilon.\]</span></p>
<p>Preto bude zápis odhadu minimalizujúceho súčet štvorcov odchýlok v maticovom zápise rovnaký ako predtým:</p>
<p><span class="math display">\[\hat \beta = (X^T X)^{-1} X^T y\]</span> Demonštrujeme si to na príklade. Chceli by sme vysvetlovať tržby na základe objemu peňazí investovaného do rôzneho typu reklamy (facebook, youtube, noviny).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datarium)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"marketing"</span>, <span class="at">package =</span> <span class="st">"datarium"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#let us try to explain sales with ads on both youtube and facebook</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marketing)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    youtube          facebook       newspaper          sales      
 Min.   :  0.84   Min.   : 0.00   Min.   :  0.36   Min.   : 1.92  
 1st Qu.: 89.25   1st Qu.:11.97   1st Qu.: 15.30   1st Qu.:12.45  
 Median :179.70   Median :27.48   Median : 30.90   Median :15.48  
 Mean   :176.45   Mean   :27.92   Mean   : 36.66   Mean   :16.83  
 3rd Qu.:262.59   3rd Qu.:43.83   3rd Qu.: 54.12   3rd Qu.:20.88  
 Max.   :355.68   Max.   :59.52   Max.   :136.80   Max.   :32.40  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube<span class="sc">+</span>facebook <span class="sc">+</span> newspaper,<span class="at">data=</span>marketing)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ youtube + facebook + newspaper, data = marketing)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5932  -1.0690   0.2902   1.4272   3.3951 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.526667   0.374290   9.422   &lt;2e-16 ***
youtube      0.045765   0.001395  32.809   &lt;2e-16 ***
facebook     0.188530   0.008611  21.893   &lt;2e-16 ***
newspaper   -0.001037   0.005871  -0.177     0.86    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.023 on 196 degrees of freedom
Multiple R-squared:  0.8972,    Adjusted R-squared:  0.8956 
F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Môžeme si všimnúť, že tržby sú pozitívne asociované s nákladami na reklamu na Youtube a Facebooku a príslušné koeficienty sú štatisticky významné. Reklama v novinách je len veľmi málo asociovaná s tržbami, dokonca negatívne ale jej koeficient nie je štatisticky významný. A táto negatívna parciálna asociácia je tam aj napriek tomu, že samotná korelácia medzi reklamou v novinách a tržbami je pozitívna. Môže to byť napríklad tým, že keď firmy inzerujú na Facebooku, tak inzerujú aj v novinách ale v skutočnosti je ta tá Facebooková reklama, ktorá zaberá. Každopádne teraz skúmame len asociácie. Nevieme, prečo v skutočnosti tržby rastú.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(<span class="fu">cor</span>(marketing), <span class="at">type =</span> <span class="st">"upper"</span>, <span class="at">order =</span> <span class="st">"hclust"</span>, </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">tl.col =</span> <span class="st">"black"</span>, <span class="at">tl.srt =</span> <span class="dv">45</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Teraz si zobrazme asociáciu medzi tržbami a štatisticky významými prediktormi (<code>youtube</code>, <code>facebook</code>), spolu s odhadnutou regresnou plochou.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we will follow https://rpubs.com/pjozefek/576206</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and modify it for our purposes</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(marketing)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> sales</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> facebook</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> youtube</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>lmodM <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmodM)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5572  -1.0502   0.2906   1.4049   3.3994 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.50532    0.35339   9.919   &lt;2e-16 ***
x1           0.18799    0.00804  23.382   &lt;2e-16 ***
x2           0.04575    0.00139  32.909   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.018 on 197 degrees of freedom
Multiple R-squared:  0.8972,    Adjusted R-squared:  0.8962 
F-statistic: 859.6 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plot3D)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>grid.lines <span class="ot">=</span> <span class="dv">20</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>x1.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(x1), <span class="fu">max</span>(x1), <span class="at">length.out =</span> grid.lines)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>x2.pred <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(x2), <span class="fu">max</span>(x2), <span class="at">length.out =</span> grid.lines)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>x1x2 <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>( <span class="at">x1 =</span> x1.pred, <span class="at">x2 =</span> x2.pred)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">predict</span>(lmodM, <span class="at">newdata =</span> x1x2), </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nrow =</span> grid.lines, <span class="at">ncol =</span> grid.lines)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>y.pred <span class="ot">&lt;-</span> <span class="fu">t</span>(y.pred)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># create the fitted points for droplines to the surface</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>fitpoints <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmodM)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># scatter plot with regression plane</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="fu">scatter3D</span>(x1, x2, y, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="dv">1</span>,<span class="at">colvar =</span> <span class="cn">NULL</span>, <span class="at">col=</span><span class="st">"red"</span>, </span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">theta =</span> <span class="sc">-</span><span class="dv">130</span>, <span class="at">phi =</span> <span class="dv">20</span>, <span class="at">bty=</span><span class="st">"b"</span>,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">xlab =</span> <span class="st">"youtube"</span>, <span class="at">ylab =</span> <span class="st">"facebook"</span>, <span class="at">zlab =</span> <span class="st">"sales"</span>,  </span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>          <span class="at">surf =</span> <span class="fu">list</span>(<span class="at">x =</span> x1.pred, <span class="at">y =</span> x2.pred, <span class="at">z =</span> y.pred,  </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>                      <span class="at">facets =</span> <span class="cn">TRUE</span>, <span class="at">fit =</span> fitpoints, </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>                      <span class="at">col=</span><span class="fu">ramp.col</span> (<span class="at">col =</span> <span class="fu">c</span>(<span class="st">"dodgerblue3"</span>,<span class="st">"seagreen2"</span>), </span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">n =</span> <span class="dv">300</span>, <span class="at">alpha=</span><span class="fl">0.9</span>), <span class="at">border=</span><span class="st">"black"</span>), </span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">"Marketing"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="nelineárne-vzťahy-a-lineárna-regresia" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="nelineárne-vzťahy-a-lineárna-regresia"><span class="header-section-number">9.8</span> Nelineárne vzťahy a lineárna regresia</h2>
<p>Niekedy je závislosť medzi dvomi premennými zjavne nelineárna. Ak sa nazdávame, že by bola vhodne modelovaná kvadratickou funkciou, potom by sme chceli fitovať nasledovný model.</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \beta_2 x^2_i + \epsilon_i,\]</span> Takýto model odhadneme nasledovne (dva spôsoby).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>marketing<span class="sc">$</span>youtube2 <span class="ot">&lt;-</span> (marketing<span class="sc">$</span>youtube)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">#lmodq &lt;- lm(sales ~ youtube + youtube2, data=marketing)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(lmod)</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>lmodq2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> <span class="fu">I</span>(youtube<span class="sc">^</span><span class="dv">2</span>), <span class="at">data=</span>marketing)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmodq2)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ youtube + I(youtube^2), data = marketing)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.2213 -2.1412 -0.1874  2.4106  9.0117 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   7.337e+00  7.911e-01   9.275  &lt; 2e-16 ***
youtube       6.727e-02  1.059e-02   6.349 1.46e-09 ***
I(youtube^2) -5.706e-05  2.965e-05  -1.924   0.0557 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.884 on 197 degrees of freedom
Multiple R-squared:  0.619, Adjusted R-squared:  0.6152 
F-statistic: 160.1 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Zo sumárnej tabuľky vidime, že kvadratický člen má pridružený p-hodnotu tesne nad <span class="math inline">\(5\%\)</span>. Na tomto obrázku to môžeme porovnať vizuálne.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>marketing, <span class="fu">aes</span>(<span class="at">x=</span>youtube, <span class="at">y=</span>sales)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,<span class="at">formula=</span><span class="st">"y ~ x"</span>) <span class="sc">+</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>,<span class="at">formula=</span><span class="st">"y ~ x + I(x^2)"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Teraz môžeme tieto myšlienky nakombinovať. Uvažujme, nech je závislosť v premennej <code>youtube</code> kvadratická a nech je v premennej <code>facebook</code> lineárna:</p>
<p><span class="math display">\[sales_i = \beta_0 + \beta_1 youtube_i + \beta_2 youtube^2_i + \beta_3 facebook_i  + \epsilon_i,\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>lmod_yt2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> <span class="fu">I</span>(youtube<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> facebook, <span class="at">data=</span>marketing)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod_yt2)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ youtube + I(youtube^2) + facebook, data = marketing)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.8632 -1.0586 -0.0598  1.1536  4.2870 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   1.545e+00  4.306e-01   3.588 0.000421 ***
youtube       7.844e-02  4.985e-03  15.736  &lt; 2e-16 ***
I(youtube^2) -9.465e-05  1.397e-05  -6.775 1.42e-10 ***
facebook      1.930e-01  7.293e-03  26.465  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.821 on 196 degrees of freedom
Multiple R-squared:  0.9167,    Adjusted R-squared:  0.9154 
F-statistic:   719 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Berúc do úvahy aj reklamu na Facebooku sa kvadratický člen pri Youtube ukazuje ako silne signifikantný.</p>
</section>
<section id="testovanie-podmodelov" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="testovanie-podmodelov"><span class="header-section-number">9.9</span> Testovanie podmodelov</h2>
<p>Ak sme v situácii, že máme 2 modely, jeden zložitejší, čo fituje dáta lepšie a jeden jednoduchší, ktorý je zasa elegantnejší. Ako sa medzi nimi rozhodujeme? Za predpokladu normality chýb na to môžeme použiť testovaciu štatistiku. Ak by bol menší model (ktorý je len špeciálnou verziou väčšieho modelu) správny, má nasledovná štatistika F rozdelenie (toto je vynormovaný podiel dvoch <a href="https://lukaslaffers.github.io/pas1/snp.html#chí-kvadrát-rozdelenie">Chí-kvadrát rozdelení</a>).</p>
<p><span class="math display">\[\frac{(RSS_{rest}-RSS_{full})/df}{\hat \sigma^2} \sim F_{df, n-p},\]</span> kde</p>
<ul>
<li><span class="math inline">\(RSS_{rest}\)</span> je reziduálna suma štvorcov menšieho (jednoduchšieho) modelu</li>
<li><span class="math inline">\(RSS_{full}\)</span> je reziduálna suma štvorcov plného (zložitejšieho) modelu</li>
<li><span class="math inline">\(df\)</span> je počet reštrikcií, ktoré z plného modelu urobia jednoduchší</li>
<li><span class="math inline">\(n\)</span> je počet pozorovaní</li>
<li><span class="math inline">\(p\)</span> je počet premenných vo veľkom modeli</li>
<li><span class="math inline">\(\sigma^2\)</span> je odhad variancie reziduí.</li>
</ul>
<p>Geometria je nasledovná</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_8_3projection_LL.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Porovnanie zložitejšieho a jednoduchšieho modelu.</figcaption>
</figure>
</div>
</div>
</div>
<p>Test toho, či je podmodel korektný, je implementovaný nasledovne:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lmod_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> <span class="fu">I</span>(youtube<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> facebook <span class="sc">+</span> newspaper, <span class="at">data=</span>marketing)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>lmod_rest <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> youtube <span class="sc">+</span> facebook, <span class="at">data=</span>marketing)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>RSS_rest <span class="ot">&lt;-</span> <span class="fu">sum</span>(lmod_rest<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>RSS_full <span class="ot">&lt;-</span> <span class="fu">sum</span>(lmod_full<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lmod_rest,lmod_full)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: sales ~ youtube + facebook
Model 2: sales ~ youtube + I(youtube^2) + facebook + newspaper
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    197 801.96                                  
2    195 649.71  2    152.25 22.847 1.217e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Teraz tieto čísla zreprodukujeme mechanicky:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get F-statistic</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># this tests null hypothesis H0:beta1=0</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>(Fstat <span class="ot">&lt;-</span> ((RSS_rest <span class="sc">-</span> RSS_full)<span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> (RSS_full<span class="sc">/</span>(<span class="dv">200-5</span>)) ) </span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.84728</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#corresponding p-value</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(Fstat,<span class="at">df1=</span><span class="dv">2</span>,<span class="at">df2=</span><span class="dv">200-5</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.217338e-09</code></pre>
</div>
</div>
<p>Tu sme testovali reštrikciu, či je kvadratický člen <code>youtube</code> nevýznamný a zároveň či je prediktor <code>newspaper</code> nevýznamný, teda či sú prislúchajúce koeficienty nulové.</p>
</section>
<section id="transformácie-a-interpretácia" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="transformácie-a-interpretácia"><span class="header-section-number">9.10</span> Transformácie a interpretácia</h2>
<p>V niektorých prípadoch modelujeme namiesto samotnej premennej jej rast. Napríklad je asi uveriteľnejšie uvažovať, že vzdelanie môže pomôcť zvýšit mzdu <strong>proporcionálne</strong>. To znamená, že absolvovanie vysokej školy zvýši mzdu v priemere približne o 20% a nie o 300eur. Rozdiel medzi 1000eur a 1300eur je totiž výraznejší z praktického hľadiska ako z 3500eur na 3800eur. Na modelovanie rastu používame logaritmickú transformáciu. Všetko si to ukážeme na našom príklade so študentami a ich výkonom na teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>hoursLearned <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">40</span>,<span class="dv">33</span>,<span class="dv">11</span>,<span class="dv">20</span>,<span class="dv">12</span>,<span class="fl">13.5</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">30</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">6</span>,<span class="dv">22</span>,<span class="dv">45</span>,<span class="dv">20</span>,<span class="dv">11</span>,<span class="dv">22</span>,<span class="dv">40</span>,<span class="dv">29</span>,<span class="dv">47</span>,<span class="dv">9</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>testScore <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">44</span>, <span class="dv">81</span>, <span class="fl">95.5</span>, <span class="fl">63.5</span>, <span class="dv">71</span>, <span class="dv">59</span>, <span class="dv">59</span>, <span class="dv">57</span>, <span class="fl">60.5</span>, <span class="dv">79</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>               <span class="dv">45</span>, <span class="dv">54</span>, <span class="dv">50</span>, <span class="dv">52</span>, <span class="dv">50</span>, <span class="dv">61</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">64</span>, <span class="dv">50</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>group <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"A"</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="st">"B"</span>,<span class="dv">10</span>))</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>gA <span class="ot">&lt;-</span> (group<span class="sc">==</span><span class="st">"A"</span>)<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>gB <span class="ot">&lt;-</span> (group<span class="sc">==</span><span class="st">"B"</span>)<span class="sc">*</span><span class="dv">1</span></span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Na konci každého modelu je korektná interpretácia. Budeme uvažovať štyri rôzne modely.</p>
<ul>
<li>Level-level model <span class="math inline">\(testScore_i = \beta_0 + \beta_1 \log(hoursLearned_i) + \beta_2 g^A_i + \epsilon_i\)</span></li>
<li>Log-level model ak budeme modelovať rast skóre pomocou hodín strávených učením <span class="math inline">\(\log(testScore_i) = \beta_0 + \beta_1 hoursLearned_i + \beta_2 g^A_i + \epsilon_i\)</span></li>
<li>Level-log model ak budeme modelovať skóre pomocou rastu hodín strávených učením <span class="math inline">\(testScore_i = \beta_0 + \beta_1 \log(hoursLearned_i) + \beta_2 g^A_i + \epsilon_i\)</span></li>
<li>Log-log model ak budeme modelovať rast skóre pomocou rastu hodín strávených učením <span class="math inline">\(\log(testScore_i) = \beta_0 + \beta_1 \log(hoursLearned_i) + \beta_2 g^A_i + \epsilon_i\)</span></li>
</ul>
<p>Ktorý z týchto modelov je najrozumnejší? Treba zvažiť. Každopádne rozhodovanie by nemalo záležať na tom, ako dobre nám modelu fituje dáta. Do rozhovorov by sme mali prizvať niekoho, kto sa vyzná do danej problematiky.</p>
<section id="level-level-model" class="level3" data-number="9.10.1">
<h3 data-number="9.10.1" class="anchored" data-anchor-id="level-level-model"><span class="header-section-number">9.10.1</span> Level-level model</h3>
<p><span class="math display">\[testScore_i = \beta_0 + \beta_1 hoursLearned_i + \beta_2 g^A_i + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#level - level</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>lmod_lv_lv <span class="ot">&lt;-</span> <span class="fu">lm</span>(testScore <span class="sc">~</span> gA <span class="sc">+</span> hoursLearned)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod_lv_lv)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = testScore ~ gA + hoursLearned)

Residuals:
     Min       1Q   Median       3Q      Max 
-19.0139  -4.0357   0.6593   3.5072  18.9040 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   39.5855     4.4224   8.951 7.65e-08 ***
gA            15.4297     3.7988   4.062 0.000811 ***
hoursLearned   0.6540     0.1426   4.585 0.000264 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.209 on 17 degrees of freedom
Multiple R-squared:  0.6376,    Adjusted R-squared:  0.595 
F-statistic: 14.96 on 2 and 17 DF,  p-value: 0.0001789</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#our model predicts that for a given group fixed an increase of </span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1hour additional learning is associated with an increase of </span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># test score by 0.65 points on average</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hoursLearned, testScore, <span class="at">pch=</span>group)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lmod_lv_lv<span class="sc">$</span>coeff[<span class="dv">1</span>],lmod_lv_lv<span class="sc">$</span>coeff[<span class="dv">3</span>])</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lmod_lv_lv<span class="sc">$</span>coeff[<span class="dv">1</span>]<span class="sc">+</span>lmod_lv_lv<span class="sc">$</span>coeff[<span class="dv">2</span>],lmod_lv_lv<span class="sc">$</span>coeff[<span class="dv">3</span>])</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretácia:</strong> Náš model predikuje, že pre danú skupinu žiakov je každá ďaľšia hodina učenia asociovaná s navýšením skóre v priemere o <span class="math inline">\(0.65\)</span>.</p>
<span class="math display">\[\begin{eqnarray*}
y_i &amp;=&amp; \beta_0 + \beta_1 x_i + \epsilon_i \\
&amp;&amp; x_i \rightarrow x_i + \Delta \\
&amp;&amp; \implies \\
y_i &amp;\rightarrow&amp; \beta_0 + \beta_1 (x_i + \Delta) + \epsilon_i  \\
y_i &amp;\rightarrow&amp; \beta_0 + \beta_1 x_i + \epsilon_i +  \beta_1 \Delta  \\
y_i &amp;\rightarrow&amp; y_i +  \beta_1 \Delta
\end{eqnarray*}\]</span>
<p>&nbsp;</p>
<p>Tu je dôležité poznamenať niekoľko skutočností</p>
<ul>
<li><em>Náš model predikuje</em> je dôležitý disclaimer a nielen slovná vata. Ide o to, že my nehovoríme o pravde, lebo nevieme aká je pravda. My hovoríme o našom lineárnom regresnom modeli, ktorý má len aproximovať realitu.</li>
<li><em>pre danú skupinu žiakov</em> znamená, že parameter <span class="math inline">\(g^A\)</span> je zafixovaný.</li>
<li><em>je asociovaná</em> neznamená, že spôsobuje. Nevieme čo spôsobuje čo, netušíme nič o kauzalite. Popisujeme ako nejaké premenné zvyknú spolu nastávať.</li>
</ul>
<p>Toto nie sú detaily. Naozaj nie. Korektná interpretácia precízne komunikuje výsledky a podčiarkuje limity použitej štatistickej metódy.</p>
</section>
<section id="log-level-model" class="level3" data-number="9.10.2">
<h3 data-number="9.10.2" class="anchored" data-anchor-id="log-level-model"><span class="header-section-number">9.10.2</span> Log-level model</h3>
<p><span class="math display">\[\log(testScore_i) = \beta_0 + \beta_1 hoursLearned_i + \beta_2 g^A_i + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#log - level</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>lmod_log_lv <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(testScore) <span class="sc">~</span> gA <span class="sc">+</span> hoursLearned)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod_log_lv)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(testScore) ~ gA + hoursLearned)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.309170 -0.043717 -0.000054  0.061891  0.225005 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.757613   0.067438  55.720  &lt; 2e-16 ***
gA           0.236549   0.057929   4.083 0.000774 ***
hoursLearned 0.010302   0.002175   4.736 0.000191 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1252 on 17 degrees of freedom
Multiple R-squared:  0.6475,    Adjusted R-squared:  0.606 
F-statistic: 15.61 on 2 and 17 DF,  p-value: 0.0001417</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#our model predicts that for a given group fixed an increase of </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1hour additional learning is associated with an increase of </span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># test score by approximately 1.03% on average</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">50</span>,<span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>dfA <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">50</span>),<span class="at">hoursLearned=</span>x)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>predA <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(lmod_log_lv,dfA))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>dfB <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">50</span>),<span class="at">hoursLearned=</span>x)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>predB <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(lmod_log_lv,dfB))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hoursLearned, testScore, <span class="at">pch=</span>group)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predA)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predB)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretácia:</strong> Náš model predikuje, že pre danú skupinu žiakov je každá ďaľšia hodina učenia asociovaná s navýšením skóre v priemer o približne <span class="math inline">\(1.03\%\)</span>.</p>
<span class="math display">\[\begin{eqnarray*}
\log(y_i) &amp;=&amp; \beta_0 + \beta_1 x_i + \epsilon_i \\
&amp;&amp; x_i \rightarrow x_i + \Delta \\
&amp;&amp; \implies \\
\log(y_i) &amp;\rightarrow&amp; \beta_0 + \beta_1 (x_i + \Delta) + \epsilon_i  \\
y_i &amp;\rightarrow&amp; e^{\beta_0 + \beta_1 (x_i + \Delta) + \epsilon_i}  \\
y_i &amp;\rightarrow&amp; e^{\beta_0 + \beta_1 x_i + \epsilon_i +  \beta_1 \Delta}  \\
y_i &amp;\rightarrow&amp; e^{\beta_0 + \beta_1 x_i + \epsilon_i}  e^{\beta_1 \Delta}  \\
y_i &amp;\rightarrow&amp; y_i e^{\beta_1 \Delta} \\
&amp;\sim&amp;\\
y_i &amp;\rightarrow&amp; y_i (1+\beta_1 \Delta)
\end{eqnarray*}\]</span>
<p>&nbsp;</p>
<p>Táto aproximácia (preto to slovo <em>približne</em>) je založená na tom, že pre malé hodnoty <span class="math inline">\(x\)</span> je funkcia <span class="math inline">\((1+\beta x)\)</span> veľmi podobná funkcii <span class="math inline">\(e^{\beta x}\)</span> ako je zobrazené na tomto obrázku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1+beta*x is similar to exp(beta*x) for small x</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">5</span>,<span class="fl">0.01</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span>beta<span class="sc">*</span>x</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta<span class="sc">*</span>x)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y1,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,y2,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="level-log-model" class="level3" data-number="9.10.3">
<h3 data-number="9.10.3" class="anchored" data-anchor-id="level-log-model"><span class="header-section-number">9.10.3</span> Level-log model</h3>
<p><span class="math display">\[testScore_i = \beta_0 + \beta_1 \log(hoursLearned_i) + \beta_2 g^A_i  + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#level - log</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>lhoursLearned <span class="ot">&lt;-</span> <span class="fu">log</span>(hoursLearned)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>lmod_lv_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(testScore <span class="sc">~</span> gA <span class="sc">+</span> lhoursLearned)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod_lv_log)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = testScore ~ gA + lhoursLearned)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.709  -3.417   0.372   3.872  17.950 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     18.257      6.801   2.684 0.015675 *  
gA              15.707      3.256   4.824 0.000159 ***
lhoursLearned   12.465      2.122   5.874 1.84e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.052 on 17 degrees of freedom
Multiple R-squared:  0.7325,    Adjusted R-squared:  0.7011 
F-statistic: 23.28 on 2 and 17 DF,  p-value: 1.354e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#our model predicts that for a given group fixed an increase of </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1% in time spent learning is associated with an increase of </span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># test score by approximately on average 0.12 points</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (hence doubling the time learning ~ +12points)</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">50</span>,<span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>lx <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">50</span>,<span class="at">by=</span><span class="dv">1</span>))</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>dfA <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">50</span>),<span class="at">lhoursLearned=</span>lx)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>predA <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmod_lv_log,dfA)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>dfB <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">50</span>),<span class="at">lhoursLearned=</span>lx)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>predB <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmod_lv_log,dfB)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hoursLearned, testScore, <span class="at">pch=</span>group)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predA)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predB)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretácia:</strong> Náš model predikuje, že pre danú skupinu žiakov je nárast učenia o 1% asociovaný s navýšením skóre v priemere o približne <span class="math inline">\(0.12\)</span>. Takže zdvojnásobnenie je asociované s približne 12 bodmi na teste.</p>
<span class="math display">\[\begin{eqnarray*}
y_i &amp;=&amp; \beta_0 + \beta_1 \log(x_i) + \epsilon_i \\
&amp;&amp; x_i \rightarrow x_i (1+\Delta) \\
&amp;&amp; \implies \\
y_i &amp;\rightarrow&amp; \beta_0 + \beta_1 \log(x_i (1+\Delta)) + \epsilon_i  \\
y_i &amp;\rightarrow&amp; \beta_0 + \beta_1 \log(x_i) +  \beta_1 \log(1+\Delta) + \epsilon_i  \\
y_i &amp;\rightarrow&amp; y_i +  \beta_1 \log(1+\Delta)\\
&amp;\sim&amp;\\
y_i &amp;\rightarrow&amp; y_i +  \beta_1 \Delta
\end{eqnarray*}\]</span>
<p>&nbsp;</p>
<p>Táto aproximácia (preto to slovo <em>približne</em>) je založená na tom, že pre malé hodnoty <span class="math inline">\(x\)</span> je funkcia <span class="math inline">\(\beta \log(1+ x)\)</span> veľmi podobná funkcii <span class="math inline">\(\beta x\)</span> ako je zobrazené na tomto obrázku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta*log(1+x) is similar to beta*x for small x</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># or </span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># log(1+x) is similar to x for small x</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.5</span>,<span class="dv">1</span>,<span class="fl">0.01</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> beta<span class="sc">*</span><span class="fu">log</span>(<span class="dv">1</span><span class="sc">+</span>x)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> beta<span class="sc">*</span>x</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y1,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,y2,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">0</span>,<span class="dv">0</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="log-log-model" class="level3" data-number="9.10.4">
<h3 data-number="9.10.4" class="anchored" data-anchor-id="log-log-model"><span class="header-section-number">9.10.4</span> Log-log model</h3>
<p><span class="math display">\[\log(testScore_i) = \beta_0 + \beta_1 \log(hoursLearned_i) + \beta_2 g^A_i  + \epsilon_i\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#log - log</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>ltestScore <span class="ot">&lt;-</span> <span class="fu">log</span>(testScore)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>lmod_log_log <span class="ot">&lt;-</span> <span class="fu">lm</span>(ltestScore <span class="sc">~</span> gA <span class="sc">+</span> lhoursLearned)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmod_log_log)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ltestScore ~ gA + lhoursLearned)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.261596 -0.044612  0.005685  0.046149  0.205080 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    3.40421    0.09547  35.658  &lt; 2e-16 ***
gA             0.24312    0.04571   5.319 5.65e-05 ***
lhoursLearned  0.20212    0.02979   6.785 3.18e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.099 on 17 degrees of freedom
Multiple R-squared:  0.7795,    Adjusted R-squared:  0.7536 
F-statistic: 30.05 on 2 and 17 DF,  p-value: 2.624e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#our model predicts that for a given group fixed an increase of </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1% in time spent learning is associated with an increase of </span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># test score by approximately 0.2% points</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (hence doubling the time learning ~ +20%points)</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">50</span>,<span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>lx <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">50</span>,<span class="at">by=</span><span class="dv">1</span>))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>dfA <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">50</span>),<span class="at">lhoursLearned=</span>lx)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>predA <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(lmod_log_log,dfA))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>dfB <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gA=</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">50</span>),<span class="at">lhoursLearned=</span>lx)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>predB <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">predict</span>(lmod_log_log,dfB))</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hoursLearned, testScore, <span class="at">pch=</span>group)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predA)</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,predB)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretácia:</strong> Náš model predikuje, že pre danú skupinu žiakov je nárast učenia o 1% asociovaný s navýšením skóre v priemerę o približne <span class="math inline">\(0.2\%\)</span> bodov. Takže zdvojnásobnenie je asociované s približne s 20% nárastom bodov na teste.</p>
<span class="math display">\[\begin{eqnarray*}
\log(y_i) &amp;=&amp; \beta_0 + \beta_1 \log(x_i) + \epsilon_i \\
&amp;&amp; x_i \rightarrow x_i (1+\Delta) \\
&amp;&amp; \implies \\
\log(y_i) &amp;\rightarrow&amp; \beta_0 + \beta_1 \log(x_i (1+\Delta)) + \epsilon_i  \\
\log(y_i) &amp;\rightarrow&amp; \beta_0 + \beta_1 \log(x_i)  + \epsilon_i +  \beta_1 \log(1+\Delta) \\
y_i &amp;\rightarrow&amp; e^{\beta_0 + \beta_1 \log(x_i)  + \epsilon_i +  \beta_1 \log(1+\Delta)}\\
y_i &amp;\rightarrow&amp; e^{\beta_0 + \beta_1 \log(x_i)  + \epsilon_i} e^{\beta_1 \log(1+\Delta)}\\
y_i &amp;\rightarrow&amp; y_i e^{\beta_1 \log(1+\Delta)}\\
y_i &amp;\rightarrow&amp; y_i e^{ \log\big((1+\Delta)^{\beta}\big)}\\
y_i &amp;\rightarrow&amp; y_i (1+\Delta)^{\beta}\\
&amp;\sim&amp;\\
y_i &amp;\rightarrow&amp; y_i (1+\beta_1 \Delta)
\end{eqnarray*}\]</span>
<p>&nbsp;</p>
<p>Táto aproximácia (znovu tu máme slovo <em>približne</em>) je založená na tom, že pre malé hodnoty <span class="math inline">\(x\)</span> je funkcia <span class="math inline">\((1+ x)^{\beta}\)</span> veľmi podobná funkcii <span class="math inline">\(1+\beta x\)</span> ako je zobrazené na tomto obrázku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (1+x)^beta is similar to (1+beta*x) for small x</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.5</span>,<span class="dv">1</span>,<span class="fl">0.01</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">+</span>x)<span class="sc">^</span>beta</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">+</span>beta<span class="sc">*</span>x</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y1,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,y2,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reg_files/figure-html/reg-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="zhrnutie" class="level2" data-number="9.11">
<h2 data-number="9.11" class="anchored" data-anchor-id="zhrnutie"><span class="header-section-number">9.11</span> Zhrnutie</h2>
<p>V tejto kapitole sme sa pozreli na kvantifikovanie lineárnej súvzťažnosti medzi dvomi premennými. Na to sme použili nástroj lineárnej regresie. Skúmali sme užitočnosť tohoto modelu ako aj štatistické vlastnosti odhadov, ktoré tento model produkuje. Potom sme pomocou lineárneho modelu používali viacero prediktorov na modelovanie nejakej premennej, ktorá nás zaujíma.</p>
</section>
<section id="cvičenia" class="level2" data-number="9.12">
<h2 data-number="9.12" class="anchored" data-anchor-id="cvičenia"><span class="header-section-number">9.12</span> Cvičenia</h2>
<!-- [R súbor k cvičeniam 18.11.2024](https://www.dropbox.com/scl/fi/5cc32hipzo6w5hj7msmik/labs_week10_2024.R?rlkey=bv1m779svscmsi9jdge1oi0m8&dl=0) -->
<!-- [R súbor k cvičeniam 25.11.2024](https://www.dropbox.com/scl/fi/ynwhj35pvs5rn2oxzyyhw/labs_week11_2024.R?rlkey=n1smbvoyim1y52k59f4tuu9cz&dl=0) -->
<!-- [R súbor s okomentovanými riešeniami](https://www.dropbox.com/scl/fi/0o6z6upbzgmsog5dny2gf/PAS_Cvicenia_kapitola8_komentare.R?rlkey=m7c2j3d8j5ohfv1abr139jbdk&dl=0) -->
<!-- [R súbor k cvičeniam 2.12.2024](https://www.dropbox.com/scl/fi/nvj6pqmy93hbcwkf4s4u5/PAS2_2Dec2024.R?rlkey=hkartadviko2t4s1xmscpymdt&dl=0) -->
<!-- [R súbor z cvičení s komentármi](https://www.dropbox.com/scl/fi/ltg828cjae7z0x9de2m7h/20231214-labs08-komentare.R?rlkey=1thlpstfht8re73bau3yv2e8p&dl=0) -->
<!-- [R súbor k cvičeniam 24.11.2022 riešenia](https://www.dropbox.com/s/ivhfnghkk21x1gd/labs_week10_solutions.R?dl=0) -->
<!-- [R súbor k cvičeniam 2.12.2022 (riešené)](https://www.dropbox.com/s/i4wldlfiuyqbb05/labs_week11.R?dl=0) -->
<p><a href="https://www.dropbox.com/scl/fi/moluuoa1dg24kpvwiekp9/cvicenie9part1.R?rlkey=a361zkhh93r8k62c0nzg3qn5p&amp;dl=0">R súbor z cvičení 24.11.2025</a></p>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.1</strong></span> Stiahnite si tieto <a href="https://www.dropbox.com/s/i7ia0n0elm1ts8l/Kompletny-prehlad-mesta-a-obce%20ciste.xlsx?dl=0">dáta</a> o veľkom Slovenskom antigénovom testovaní z roku 2020. Skúmajte aký je vzťah medzi percentom nakazených v prvom a v druhom kole testovania pre rôzne obce. Pozrite sa oddelene na malé, stredné a veľké obce.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.2</strong></span> Mechanicky spočítajte ESS, RSS a ESS a overte ich vzťah. Potom zrátajte <span class="math inline">\(R^2\)</span> a porovnajte s výsledkom v sumárnej tabuľke.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.3</strong></span> Mechanicky zreprodukujte všetky výsledky (okrem adjusted <span class="math inline">\(R^2\)</span>) zo sumárnej tabuľke. (Toto je užitočné cvičenie.)</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.4</strong></span> Stiahnite si dataset <code>cars</code> z knižnice <code>dataset</code>. Zobrazte závislosť medzi brzdnou dráhou a rýchlosťou (brzdná dráha bude vysveltovaná premenná) a popíšte ich vzťah aj pomocou jednoduchého lineárneho regresného modelu. Odhadnite koeficienty pomocou funkcie <code>lm</code> a interpretujte výsledky v sumárnej tabuľke.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.5</strong></span> Z datasetu <code>movies</code> z knižnice <code>ggplot2movies</code> sa pozrite, či veľkosť rozpočtu vie predikovať priemerné hodnotenie. Na túto závislosť sa pozrite pre rôzne typy filmov a dáta spolu s regresnými priamkami vhodne zobrazte. Kriticky zhodnoťte model a výsledky opatrne interpretujte.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.6</strong></span> Z datasetu <code>USArrests</code> porovnajte úrovne rôznych zločinov podľa toho, či žije v mestách veľa ľudí (<span class="math inline">\(y\)</span> budú <code>Murder</code>,<code>Assault</code>,<code>Rape</code> a <span class="math inline">\(x\)</span> bude <code>UrbanPop</code> ). Dáta zobrazte. Odhadnite koeficienty pomocou funkcie <code>lm</code> a interpretujte výsledky v sumárnej tabuľke.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.7</strong></span> Z datasetu <code>movies</code> z knižnice <code>ggplot2movies</code> sa znovu pozrieme na predikciu priemerného hodnotenia. Pozrite sa, či typ filmu, rozpočet a dĺžka filmu vedia predikovať hodnotenie.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 9.8</strong></span> Majme nasledovné dve skupiny študentov. Zaujíma nás, ako je počet hodín strávených učením asociovaný s dosiahnutým skóre v teste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># you measure how much they learned</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>hoursLearned <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">40</span>,<span class="dv">33</span>,<span class="dv">11</span>,<span class="dv">20</span>,<span class="dv">12</span>,<span class="fl">13.5</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">30</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                  <span class="dv">6</span>,<span class="dv">22</span>,<span class="dv">45</span>,<span class="dv">20</span>,<span class="dv">11</span>,<span class="dv">22</span>,<span class="dv">40</span>,<span class="dv">29</span>,<span class="dv">47</span>,<span class="dv">9</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># and how they performed on a test</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>testScore <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">44</span>, <span class="dv">81</span>, <span class="fl">95.5</span>, <span class="fl">63.5</span>, <span class="dv">71</span>, <span class="dv">59</span>, <span class="dv">59</span>, <span class="dv">57</span>, <span class="fl">60.5</span>, <span class="dv">79</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>               <span class="dv">45</span>, <span class="dv">54</span>, <span class="dv">50</span>, <span class="dv">52</span>, <span class="dv">50</span>, <span class="dv">61</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">64</span>, <span class="dv">50</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># and how they performed on a test</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co">#there are two different groups of students</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>group <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"A"</span>,<span class="dv">10</span>), <span class="fu">rep</span>(<span class="st">"B"</span>,<span class="dv">10</span>))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Využitím lineárneho modelu uvažujte ako sú tieto dve skupiny rôzne: čo sa týka priemerného testovacieho skóre ako aj čo sa týka citlivosti skóre na učenie.</p>
</div>
<!-- ## Domáca úloha 4 -->
<!-- Deadline je 13.12.2024 o 20:00. Váš kód aj ostatné pomocné súbory (napríklad dáta) mi zabaľte do jedného (1) zip súboru (nie `rar` súbor, nie OneDrive folder) v tvare `du4_MenoPriezvisko.zip` (napr. `du4_PeterKovac.zip`) a pošlite cez formulár, ktorého odkaz je na stránke. Kód musí byť spustiteľný a podrobne okomentovaný. Odovzdávate mi Vašu **vlastnú** prácu. Domáca úloha je **dobrovoľná** a **nehodnotená**. V prípade, že ju pošlete do termínu dostanete spätnú väzbu -->
<!-- Dáta sú vymyslené, [stiahnete si ich tu](https://www.dropbox.com/scl/fi/5bz3q2rusd6f0ys3gdd57/du4-data.R?rlkey=0nmap4wm3emv7w626akg2sxvh&dl=0). Všetky vaše zistenia podrobne okomentujte a podporte vhodným obrázkom. -->
<!-- ::: {.exercise name="DÚ 4.1 teplota"} -->
<!-- Na niekoľkých meracích staniciach máme údaje o teplote, hĺbke jazera a jeho nadmorskej výške. -->
<!-- a)  Urobte jednoduchý lineárny model vysvetľujúci teplotu pomocou nadmorskej výšky jazera. Odhadnite teplotu jazera v nadmorskej výške 1100 m.n.m. a 1250 m.n.m. Tieto predpovede farebne vyznačte do vykresleného grafu. Odhadnite, o koľko sa zmení teplota nejakého jazera, pokiaľ by sa nachádzalo o 100 výškových metrov vyššie alebo nižšie. -->
<!-- b)  Urobte jednoduchý lineárny model vysvetľujúci teplotu pomocou hĺbky jazera a porovnajte ho s prvým lineárnym modelom. Odhadnite teplotu jazera s hĺbkou 22 m. -->
<!-- c)  Urobte lineárny model vysvetľujúci teplotu pomocou nadmorskej výšky aj hĺbky jazera a určte, ktorý z troch modelov je najlepší. Odhadnite teplotu pre jazero v nadmorskej výške 1100 m.n.m. s hĺbkou 22 m. -->
<!-- ::: -->
<!-- ::: {::: {.Exercise #exr-}} -->
<!-- Urobte jednoduchý lineárny model, kde hodnoty y budete predpovedať pomocou hodnôt x. Pomocou obrázku zistite, či je lineárny model vhodný na takýto typ dát. Pokúste sa spraviť lepší lineárny model a porovnajte ho s predošlým. -->
<!-- a)  dáta x1, y1 z priloženého R-kódu. -->
<!-- b)  dáta x2, y2 z priloženého R-kódu. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 4.3 - Filmy a Rmd Projekt"} -->
<!-- Pozrite sa do datasetu `movies` z knižnice `ggplot2movies`. Vaše zadanie je vyprodukovať ucelený report o prediktoroch hodnotenia filmu. Zaujíma nás vzťah medzi hodnotením filmu a jeho rozpočtom ako aj dĺžkou a typom filmu. -->
<!-- Vyberte len relevantné hodnotenia. -->
<!-- Bude obsahovať -->
<!-- -   Krátky popis datasetu, premenných a problému, ktorý skúmame, -->
<!-- -   Sumárne štatistiky premenných, -->
<!-- -   Párové grafy a korelácie, -->
<!-- -   Porovnanie rôznych podskupín pomocou vhodných štatistických testov a zobrazení. -->
<!-- -   Rozumne zvolený lineárny model, -->
<!-- -   Závery, interpretácie a zistenia. Nepodceňte túto časť. -->
<!-- Dokument -->
<!-- -   musí byť čitateľný pre *úplného laika*, -->
<!-- -   musí byť vytvorený v RMarkdown, -->
<!-- -   všetok kód musí byť schovaný ale vhodne okomentovaný v `rmd` súbore, -->
<!-- -   obrázky musia byť vyladené, musia mať vhodne zvolené vizuálne elementy ako aj popisy, -->
<!-- -   môžete ale nemusíte písať v angličtine, -->
<!-- -   k tejto úlohe mi prosím pošlite dva súbory: `Rmd` súbor a `html` súbor. -->
<!-- Bude to demonštrácia, vizitka a oslava všetkého toho, čo ste sa naučili. -->
<!-- ::: -->


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Skopírované!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Skopírované!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ttest.html" class="pagination-link" aria-label="Štatistické testovanie hypotéz">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Štatistické testovanie hypotéz</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./report.html" class="pagination-link" aria-label="Komunikácia výsledkov">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Komunikácia výsledkov</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>