<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="sk" xml:lang="sk"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Štatistické testovanie hypotéz – Pravdepodobnosť a štatistika 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./reg.html" rel="next">
<link href="./visual.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-626149efe8f5d16e1d391ba177679bf0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Žiadne výsledky",
    "search-matching-documents-text": "zhodné dokumenty",
    "search-copy-link-title": "Skopírovať odkaz pre vyhľadávanie",
    "search-hide-matches-text": "Skryť ďalšie výsledky",
    "search-more-match-text": "ďalší výsledok v tomto dokumente",
    "search-more-matches-text": "ďalších výsledkov v tomto dokumente",
    "search-clear-button-title": "Vymazať",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Zrušiť",
    "search-submit-button-title": "Odoslať",
    "search-label": "Hľadať"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Prepnúť postrannú navigáciu" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ttest.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Štatistické testovanie hypotéz</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Prepnúť postrannú navigáciu" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Hľadať" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Pravdepodobnosť a štatistika 2</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Hľadať"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">O tomto kurze</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Úvod do jazyka R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Premenné a dátové štruktúry</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Náhodné čísla a simulácie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Čistenie dát</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Zopakovanie pojmov</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./depen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Náhodné vektory a súvis medzi náhodnými premennými</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visual.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Zobrazovanie dát</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ttest.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Štatistické testovanie hypotéz</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Úvod do lineárnej regresie</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Komunikácia výsledkov</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Obsah</h2>
   
  <ul>
  <li><a href="#jedno" id="toc-jedno" class="nav-link active" data-scroll-target="#jedno"><span class="header-section-number">8.1</span> Jednovýberové testy</a>
  <ul class="collapse">
  <li><a href="#test-na-základe-normálnej-aproximácie-z-test" id="toc-test-na-základe-normálnej-aproximácie-z-test" class="nav-link" data-scroll-target="#test-na-základe-normálnej-aproximácie-z-test"><span class="header-section-number">8.1.1</span> Test na základe normálnej aproximácie (Z-test)</a></li>
  <li><a href="#t-test" id="toc-t-test" class="nav-link" data-scroll-target="#t-test"><span class="header-section-number">8.1.2</span> T-test</a></li>
  </ul></li>
  <li><a href="#dvojvýberové-testy" id="toc-dvojvýberové-testy" class="nav-link" data-scroll-target="#dvojvýberové-testy"><span class="header-section-number">8.2</span> Dvojvýberové testy</a>
  <ul class="collapse">
  <li><a href="#rovnaká-variancia" id="toc-rovnaká-variancia" class="nav-link" data-scroll-target="#rovnaká-variancia"><span class="header-section-number">8.2.1</span> Rovnaká variancia</a></li>
  <li><a href="#rôzna-variancia" id="toc-rôzna-variancia" class="nav-link" data-scroll-target="#rôzna-variancia"><span class="header-section-number">8.2.2</span> Rôzna variancia</a></li>
  <li><a href="#párové-testy" id="toc-párové-testy" class="nav-link" data-scroll-target="#párové-testy"><span class="header-section-number">8.2.3</span> Párové testy</a></li>
  </ul></li>
  <li><a href="#porovnanie-stredných-hodnôt-viacerých-vzoriek-anova" id="toc-porovnanie-stredných-hodnôt-viacerých-vzoriek-anova" class="nav-link" data-scroll-target="#porovnanie-stredných-hodnôt-viacerých-vzoriek-anova"><span class="header-section-number">8.3</span> Porovnanie stredných hodnôt viacerých vzoriek (ANOVA)</a></li>
  <li><a href="#konfidenčný-interval" id="toc-konfidenčný-interval" class="nav-link" data-scroll-target="#konfidenčný-interval"><span class="header-section-number">8.4</span> Konfidenčný interval</a></li>
  <li><a href="#testovanie-podielu" id="toc-testovanie-podielu" class="nav-link" data-scroll-target="#testovanie-podielu"><span class="header-section-number">8.5</span> Testovanie podielu</a>
  <ul class="collapse">
  <li><a href="#testovanie-podielu-pre-jednu-skupinu" id="toc-testovanie-podielu-pre-jednu-skupinu" class="nav-link" data-scroll-target="#testovanie-podielu-pre-jednu-skupinu"><span class="header-section-number">8.5.1</span> Testovanie podielu pre jednu skupinu</a></li>
  <li><a href="#testovanie-rovnosti-podielov-pre-dve-skupiny" id="toc-testovanie-rovnosti-podielov-pre-dve-skupiny" class="nav-link" data-scroll-target="#testovanie-rovnosti-podielov-pre-dve-skupiny"><span class="header-section-number">8.5.2</span> Testovanie rovnosti podielov pre dve skupiny</a></li>
  </ul></li>
  <li><a href="#kontigenčné-tabuľky" id="toc-kontigenčné-tabuľky" class="nav-link" data-scroll-target="#kontigenčné-tabuľky"><span class="header-section-number">8.6</span> Kontigenčné tabuľky</a></li>
  <li><a href="#zopár-poznámok-na-záver." id="toc-zopár-poznámok-na-záver." class="nav-link" data-scroll-target="#zopár-poznámok-na-záver."><span class="header-section-number">8.7</span> Zopár poznámok na záver.</a></li>
  <li><a href="#prehľad" id="toc-prehľad" class="nav-link" data-scroll-target="#prehľad"><span class="header-section-number">8.8</span> Prehľad</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="ttest" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Štatistické testovanie hypotéz</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Majme dve skupiny a chceli by sme vedieť, či sú tieto skupiny rôzne.</p>
<ul>
<li>Líšia sa pacienti, ktorí dostali inovatívnu liečbu od tých ktorí dostali tradičnú liečbu?</li>
<li>Majú študenti/tky z osemročných gymnázií lepšie výsledky ako tí/tie zo štvorročných gymnázií?</li>
<li>Sú čitatelia denníka Alobal náchylnejší na podľahnutie konšpiráciám?</li>
<li>Zarábajú viacej absolventi štúdijného odboru matematika alebo kombinovaného štúdijného odboru záhradkárstvo a kulturistika?</li>
</ul>
<p>Máme však v dispozícii len vzorku limitovanej veľkosti. Častokrát nás zaujíma, či sa tieto dve skupiny líšia v <strong>strednej hodnote</strong>. Nie je to samozrejme úplne to isté, ako to, že sú celé distribúcie týchto dvoch skupín rovnaké ale je to dobrý štart. A je to zaujímavé a zrozumiteľné.</p>
<p>&nbsp;</p>
<p>Začnime jednoduchým príkladom. Porovnajme dve vzorky náhodných premenných. Jedna náhodná premenná bude mať strednú hodnotu 1, druhá 1.2. <span class="math inline">\(X_1 \sim N(1,1)\)</span> a <span class="math inline">\(X_2 \sim N(1.2,1).\)</span></p>
<p>Vygenerujme si vzorky veľkosti 30 a zakreslime:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">54459</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sim_hist <span class="ot">&lt;-</span> <span class="cf">function</span>(mu1, mu2, <span class="at">nSim=</span><span class="dv">20</span>){</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  data_mu <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">variable=</span><span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"X_1"</span>, <span class="st">"X_2"</span>), <span class="at">each=</span>nSim)),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">value=</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(nSim, <span class="at">mean=</span>mu1, <span class="at">sd=</span><span class="dv">1</span>), </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">rnorm</span>(nSim, <span class="at">mean=</span>mu2, <span class="at">sd=</span><span class="dv">1</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  mu <span class="ot">&lt;-</span> data_mu <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">group_means =</span> <span class="fu">mean</span>(value))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  g <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data_mu, <span class="fu">aes</span>(<span class="at">x=</span>value, <span class="at">color=</span>variable, <span class="at">fill=</span>variable)) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">position=</span><span class="st">"identity"</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">alpha=</span><span class="fl">0.5</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bins=</span><span class="dv">30</span>)<span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">data=</span>mu, <span class="fu">aes</span>(<span class="at">xintercept=</span>group_means, <span class="at">color=</span>variable),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype=</span><span class="st">"dashed"</span>)<span class="sc">+</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">data=</span>mu, <span class="fu">aes</span>(<span class="at">x=</span>group_means,<span class="at">y=</span><span class="fl">0.7</span>, <span class="at">hjust=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                           <span class="at">label=</span> <span class="fu">as.character</span>(<span class="fu">round</span>(group_means,<span class="dv">2</span>)), <span class="at">color=</span>variable))<span class="sc">+</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste0</span>(<span class="st">"Histogram (n = "</span>,nSim,<span class="st">")"</span>),<span class="at">x=</span><span class="st">"Values"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)<span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(g)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,<span class="cf">function</span>(n) <span class="fu">sim_hist</span>(<span class="dv">1</span>,<span class="fl">1.2</span>,<span class="dv">30</span>))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(g[[<span class="dv">1</span>]],g[[<span class="dv">2</span>]],g[[<span class="dv">3</span>]],</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>          g[[<span class="dv">4</span>]],g[[<span class="dv">5</span>]],g[[<span class="dv">6</span>]],</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">labels =</span> <span class="st">"AUTO"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Je <span class="math inline">\(n=30\)</span> pozorovaní dosť na to, aby sme rozlíšili medzi týmito dvomi vzorkami? Nezabúdajme, že v realite máme len <strong>jednu</strong> vzorku.</p>
<p>Skúsme <span class="math inline">\(n=300.\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,<span class="cf">function</span>(n) <span class="fu">sim_hist</span>(<span class="dv">1</span>,<span class="fl">1.2</span>,<span class="dv">300</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(g[[<span class="dv">1</span>]],g[[<span class="dv">2</span>]],g[[<span class="dv">3</span>]],</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>          g[[<span class="dv">4</span>]],g[[<span class="dv">5</span>]],g[[<span class="dv">6</span>]],</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">labels =</span> <span class="st">"AUTO"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>OK, lepšie.</p>
<p>Skúsme teraz <span class="math inline">\(n=10000.\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,<span class="cf">function</span>(n) <span class="fu">sim_hist</span>(<span class="dv">1</span>,<span class="fl">1.2</span>,<span class="dv">10000</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_grid</span>(g[[<span class="dv">1</span>]],g[[<span class="dv">2</span>]],g[[<span class="dv">3</span>]],</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>          g[[<span class="dv">4</span>]],g[[<span class="dv">5</span>]],g[[<span class="dv">6</span>]],</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">labels =</span> <span class="st">"AUTO"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vyskúšali sme si a dozvedeli sme sa jednu neprekvapivú vec. S rastúcim počtom pozorovaní vieme dobre odlíšiť aj malý rozdiel medzi premennými.</p>
<p>V realite my samozrejme nevieme z akej distribúcie tie dve vzorky pochádzajú.</p>
<section id="jedno" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="jedno"><span class="header-section-number">8.1</span> Jednovýberové testy</h2>
<p>Teraz budeme mať len jednu vzorku pozorovaní. Náhodnú iid vzorku veľkosti <span class="math inline">\(n\)</span>.</p>
<section id="test-na-základe-normálnej-aproximácie-z-test" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="test-na-základe-normálnej-aproximácie-z-test"><span class="header-section-number">8.1.1</span> Test na základe normálnej aproximácie (Z-test)</h3>
<p>Začneme najjednoduchším prípadom. Prepokladajme, že naše pozorovania pochádzajú z normálneho rozdelenia s neznámou strednou hodnotou a s neznámou varianciou. Nech ide o zmenu výsledku na teste. Študent absolvuje test na začiatku semestra a potom (podobný) test na konci semestra. A chceli by sme vedieť či sa výsledky zlepšili. Teda, že či sa študenti niečo naučili.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">437</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_test <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">cas=</span><span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"pred"</span>, <span class="st">"po"</span>), <span class="at">each=</span><span class="dv">30</span>)),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">test=</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean=</span><span class="dv">50</span>, <span class="at">sd=</span><span class="dv">10</span>), </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="at">mean=</span><span class="dv">65</span>, <span class="at">sd=</span><span class="dv">5</span>))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                          )</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>zmena <span class="ot">&lt;-</span> data_test<span class="sc">$</span>test[<span class="fu">which</span>(data_test<span class="sc">$</span>cas<span class="sc">==</span><span class="st">"po"</span>)] <span class="sc">-</span> data_test<span class="sc">$</span>test[<span class="fu">which</span>(data_test<span class="sc">$</span>cas<span class="sc">==</span><span class="st">"pred"</span>)]</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="fu">as.data.frame</span>(zmena),<span class="fu">aes</span>(<span class="at">x=</span>zmena)) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span>..density..), <span class="at">position=</span><span class="st">"identity"</span>, </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">alpha=</span><span class="fl">0.5</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bins=</span><span class="dv">30</span>)<span class="sc">+</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.6</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(zmena)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.25302</code></pre>
</div>
</div>
<p>Väčšina študentov sa zlepšila ale nájdu sa aj takí, ktorí sa dokonca zhoršili, konkrétne traja. Priemerné zlepšenie je <span class="math inline">\(18.25\)</span>.</p>
<p>Chceli by sme vedieť či je stredná hodnota väčšia ako <span class="math inline">\(15\)</span> alebo nie. Nuž vidíme, že v našom prípade je o <span class="math inline">\(3.25\)</span> viacej. Ako veľmi si ale môžeme byť tým istí?</p>
<p>Na to aby sme to vedeli posúdiť potrebujeme nejakým spôsobom odhadnúť ako veľa je variability v tom čísle <span class="math inline">\(18.25,\)</span> ako blízko by sme očakávali, že má byť k čislu 15. Ako sme videli, čím viacej máme pozorovaní tým menej neistoty je v tom, ako ďaleko je tento aritmetický priemer (18.25) od skutočného populačného priemeru (15). Zo sekcie o <a href="https://lukaslaffers.github.io/pas1/zvc.html">zákone o veľkých čislach</a> vieme, že</p>
<p>Ak <span class="math inline">\(X_1, X_2, X_3, \dots {\text{iid} }, \text{E}[X_1] = \mu, \text{Var}[X_1] = \sigma^2 \implies \bar{X}_n \equiv \frac{X_1 + X_2 + \dots + X_n}{n} \rightarrow_D N(\mu, \frac{\sigma^2}{n}),\)</span></p>
<p>pokiaľ <span class="math inline">\(X_1, X_2,...\)</span> sú združene nezávislé a rovnako rozdelené (iid = independent and identically distributed) náhodné premenné.</p>
<p>Takže vidíme, že variancia nášho odhadu klesá proporionálne veľkosti dátovej vzorky <span class="math inline">\(n.\)</span></p>
<p>Z tohoto máme, že <span class="math display">\[\sqrt{n}(\bar{X}_n - \mu) \rightarrow_D N(0,\sigma^2),\]</span> takže <span class="math display">\[\sqrt{n}\frac{\bar{X}_n - \mu}{\sigma} \rightarrow_D N(0,1).\]</span> Čo nám z toho vyplýva? Nuž, že vieme čosi povedať o pravdepodobnostnom správaní priemeru, za predpokladu, že vieme strednú hodnotu <span class="math inline">\(\mu\)</span> a varianciu <span class="math inline">\(\sigma^2.\)</span> A čo s tou smerodajnou odchýlkou <span class="math inline">\(\sigma\)</span>? Vieme ju odhadnúť pomocou výberovej smerodajnej odchýlky <span class="math inline">\(S,\)</span> ktorá je odmocninou z výberovej variancie <span class="math inline">\(S^2\)</span>:</p>
<p><span class="math display">\[S^2 = \frac{\sum_{i=1}^n(X_i - \bar{X}_n)^2}{n-1}.\]</span> Vieme, že <span class="math inline">\(S^2 \rightarrow_P \sigma^2,\)</span> kde symbol <span class="math inline">\(\rightarrow_P\)</span> označuje <a href="https://lukaslaffers.github.io/pas1/zvc.html#konvergencia-podľa-pravdepodobnosti">konvergenciu podľa pravdepodobnosti</a>. Preto</p>
<p><span class="math display">\[Z \equiv \sqrt{n}\frac{\bar{X}_n - \mu}{S} \rightarrow_D N(0,1).\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>( S2 <span class="ot">&lt;-</span> <span class="fu">sum</span>((zmena<span class="sc">-</span><span class="fu">mean</span>(zmena))<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="fu">length</span>(zmena)<span class="sc">-</span><span class="dv">1</span>)) )</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154.5722</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(zmena) </span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 154.5722</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">var</span>(zmena))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.43271</code></pre>
</div>
</div>
<p>Čo sme sa dozvedeli? Ak by bola stredná hodnota <span class="math inline">\(\mu\)</span> skutočne rovná 15, potom by <span class="math inline">\(Z\)</span> mala byť (približne) <span class="math inline">\(N(0,1)\)</span> rozdelená.</p>
<p>V našom prípade máme len jednu realizáciu <span class="math inline">\(Z\)</span>, a to konkrétne <span class="math display">\[\sqrt{30}\frac{18.25-15}{12.43} = 1.43.\]</span> Ako veľmi je táto jedna hodnota 1.43 <strong>kompatibilná</strong> s normálnym rozdelením? Pozrime sa na obrázok.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>x  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>,<span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>fx <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>x,<span class="at">y=</span>fx)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(x,y)) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fl">1.43</span>, <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"hustota N(0,1)"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ako to kvantifikovať? No môžeme spočítať pravdepodobnosť ešte <strong>extrémnejšej situácie</strong>. To je oblasť vyšrafovaná nižšie:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A je rovná <span class="math display">\[\int_{1.43}^{\infty} \phi(x) dx = 1-\Phi(1.43) = 0.076,\]</span> kde</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fl">1.43</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.07635851</code></pre>
</div>
</div>
<p><span class="math inline">\(\phi(x) = \frac{1}{2\pi}e^{-\frac{x^2}{2}},\)</span> takže funkcia hustoty <a href="https://lukaslaffers.github.io/pas1/snp.html#normálne-rozdelenie">normovaného normálneho rozdelenia</a>.</p>
<p>To znamená, že ak by sme opakovali takýto pokus</p>
<ul>
<li>zozbierali 30 iid pozorovaní</li>
<li>skutočná stredná hodnota bola <span class="math inline">\(\mu = 15\)</span></li>
<li>spočítali sme <span class="math inline">\(S^2\)</span> a následne <span class="math inline">\(Z = \sqrt{n}\frac{\bar{X}_n - \mu}{S}\)</span></li>
</ul>
<p>Tak takéto <span class="math inline">\(Z\)</span> by malo normálne rozdelenie a hodnotu väčšiu ako 1.43 by sme dostali zhruba v <span class="math inline">\(7.6\%\)</span> prípadov. Je to veľa, je to málo? To záleží od toho ako veľmi ste ochotní sa mýliť. Každopádne je to číslo zrozumiteľné a hovorí nám to <strong>ako veľmi je číslo</strong> <span class="math inline">\(\mu = 15\)</span> kompatibilné s našimi dátami. Tomuto hovoríme <strong>jednostranný test</strong> nulovej hypotézy <span class="math inline">\(\mu=15\)</span> voči alternatíve <span class="math inline">\(\mu &gt; 15\)</span> na základe normálnej aproximácie. Hodnota 0.076 sa nazýva <strong>p-hodnota</strong> tohoto testu.</p>
<p>Mohli by sme uvažovať extrémnosť situácie oboma smermi. Takže by sme pripúšťali, že študenti sa môžu zlepšiť aj menej ako o 15 bodov. V tom prípade by sme kvantifikovali kompatibilnosť 1.43 s dátami takto:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kedže distribúcia normovanej normálnej náhodnej premennej je symetrická, dostávame <span class="math display">\[\int_{-\infty}^{-1.43} \phi(x) dx + \int_{1.43}^{\infty} \phi(x) dx = \Phi(-1.43) + 1-\Phi(1.43)= 2(1-\Phi(1.43)) = 2 \cdot 0.076 = 0.152.\]</span> Tomuto hovoríme <strong>obojstranný test</strong> nulovej hypotézy <span class="math inline">\(\mu=15\)</span> voči alternatíve <span class="math inline">\(\mu \neq 15\)</span> na základe normálnej aproximácie. Hodnota 0.152 sa nazýva <strong>p-hodnota</strong> tohoto testu.</p>
<p>&nbsp;</p>
<p>Ako to funguje v praxi? Tu je vysvetlenie spolu so <strong>slovníkom</strong>:</p>
<ul>
<li>Zvolím si <strong>nulovú hypotézu</strong>, ktorú chcem otestovať (napr. <span class="math inline">\(\mu=15\)</span>). K nej si zvolím <strong>alternatívnu hypotézu</strong> (napr. <span class="math inline">\(\mu &gt; 15\)</span>).</li>
<li>Zvolím si <strong>hladinu významnosti</strong> <span class="math inline">\(\alpha\)</span>. Napríklad <span class="math inline">\(\alpha = 0.05.\)</span> To znamená, že si poviem, ako veľmi som ochotný sa mýliť v zmysle, že zamietnem pravdivú hypotézu.</li>
<li>Ak je moja p-hodnota testu menšia ako hladina významnosti <span class="math inline">\(\alpha,\)</span> potom <strong>zamietam</strong> nulovú hypotézu. To znamnená, že vzhľadom na moju fixnú ochotu mýliť sa, je hodnota testovacej štatistiky príliš extrémna na to, aby bola kompatibilná s mojou hypotézou.</li>
<li>Ak je moja p-hodnota testu väčšia ako hladina významnosti <span class="math inline">\(\alpha,\)</span> potom <strong>nezamietam</strong> nulovú hypotézu. {} Znamená to, že nemám dosť dôkazov na to, aby som ju zamietol, vzhľadom na to, koľko som ochotný sa mýliť.</li>
<li>Náhodnú premennú <span class="math inline">\(Z\)</span> nazývame <strong>testovacia štatistika</strong> a takú hodnotu <span class="math inline">\(c\)</span>, že platí <span class="math inline">\(P(Z &gt; c) = \alpha\)</span> v prípade jednostranného testu a <span class="math inline">\(P(|Z| &gt; c) = \alpha\)</span> v prípade obojstranného testu, nazývame <strong>kritická hodnota testu</strong>. Napríklad kritická hodnota obojstranného testu na hladine významnosti <span class="math inline">\(0.05\)</span> je <span class="math inline">\(1.96,\)</span> lebo <span class="math inline">\(P(|Z|&gt;1.96)=0.05.\)</span></li>
</ul>
<p>&nbsp;</p>
<p>V Rku zbehneme test veľmi jednoducho.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One-sample z-Test

data:  zmena
z = 1.4331, p-value = 0.07591
alternative hypothesis: true mean is greater than 15
95 percent confidence interval:
 14.51938       NA
sample estimates:
mean of x 
 18.25302 </code></pre>
</div>
</div>
<section id="intuícia" class="level4" data-number="8.1.1.1">
<h4 data-number="8.1.1.1" class="anchored" data-anchor-id="intuícia"><span class="header-section-number">8.1.1.1</span> Intuícia</h4>
<p>Takže ešte raz. Predstavme si, že testovacia štatistika bude obrovská a p-hodnota veľmi veľmi malá.</p>
<ul>
<li>Ak by platila nulová hypotéza, tak by som naozaj neočakával takú veľkú hodnotu testovacej štatistiky.</li>
<li>Akože áno, môže to nastať ale šanca je veľmi malá.</li>
<li>Niečo asi nie je v poriadku.</li>
<li>Ak verím ostatným modelovým predpokladom, tak jediné čo mi zostáva je, že asi tá nulová hypotéza predsalen neplatí.</li>
<li>Správnu nulovú hypotézu môžem zamietať <span class="math inline">\(100\alpha\%\)</span> krát, tak ak mi vychádza p-hodnota, že to čo vidím nastáva raz za milión pokusov (p-hodnota je 0.000001), tak je naozaj asi rozumné zamietnuť túto nulovú hypotézu.</li>
<li>Každopádne nezabúdam, že toto všetko rozhodovanie je na základe <strong>jednej jedinej</strong> realizácie testovacej štatistiky. Nuž ale nič lepšie nemám.</li>
</ul>
</section>
</section>
<section id="t-test" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="t-test"><span class="header-section-number">8.1.2</span> T-test</h3>
<p>V prípade, že <span class="math inline">\(X_1, X_2, X_3, \dots\)</span> nielenže sú iid, ale ak sú dokonca aj normálne rozdelené, takže ak <span class="math inline">\(X_1 \sim N(\mu,\sigma^2),\)</span> potom môžeme naše výsledky spresniť, budeme môcť <strong>presne popísať pravdepodobnostné správanie testovacej štatistiky</strong>. Predtým sme využili, že <span class="math inline">\(Z \rightarrow_D N(0,1).\)</span> No ale čo ak máme len málo pozorovaní? Vtedy nemôžeme použiť asymptotickú aproximáciu, tá funguje len ak máme dostatočne veľa pozorovaní, teda ak <span class="math inline">\(n\)</span> je dostatočne veľké.</p>
<p>Keď sú však <span class="math inline">\(X_1 \sim N(\mu,\sigma^2)\)</span> (kedže postupnosť <span class="math inline">\(X_1, X_2,X_3,\dots\)</span> je iid, tak aj <span class="math inline">\(X_i \sim N(\mu,\sigma^2)\)</span> pre <span class="math inline">\(i = 1,2,3,\dots.\)</span>), tak potom priamo vieme rozdelenie náhodnej premennej <span class="math inline">\(\sqrt{n}\frac{\bar{X}_n - \mu}{S}\)</span>, ktorú teraz premenujeme na T.</p>
<p><span class="math display">\[T \equiv \sqrt{n}\frac{\bar{X}_n - \mu}{S} \sim t_{n-1}\]</span> To preto lebo má <a href="https://lukaslaffers.github.io/pas1/snp.html#studentovo-rozdelenie-t-rozdelenie">t-rozdelenie s <span class="math inline">\(n-1\)</span> stupňami voľnosti</a>.</p>
<p>Pre dostatočne veľký počet pozorovaní je len maličký rozdiel medzi <span class="math inline">\(t-\)</span>rozdelením a <span class="math inline">\(N(0,1)\)</span> rozdelením.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Môžeme ísť naspäť k nášmu príkladu so študentami a pozrieť sa na porovnanie medzi testom na základe normálnej aproximácie a t-testom. Priblížime na relevantnú oblasť, aby sme to vedeli porovnať.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>P-hodnota testu je iná, je to 0.0817, takže t-rozdelenie prisudzuje chvostom väčšiu váhu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">1.43</span>,<span class="at">df=</span><span class="dv">29</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08170164</code></pre>
</div>
</div>
<p>V praxi je to však veľmi jednoduché, stačí takýto príkaz a nemusíme nič počítať sami.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(zmena, <span class="at">alternative=</span><span class="st">"greater"</span>,<span class="at">mu=</span><span class="dv">15</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  zmena
t = 1.4331, df = 29, p-value = 0.08126
alternative hypothesis: true mean is greater than 15
95 percent confidence interval:
 14.39619      Inf
sample estimates:
mean of x 
 18.25302 </code></pre>
</div>
</div>
</section>
</section>
<section id="dvojvýberové-testy" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="dvojvýberové-testy"><span class="header-section-number">8.2</span> Dvojvýberové testy</h2>
<p>Myšlienka ostáva tá istá. Jediné, čo sa mení, je <strong>testovacia štatistika</strong>.</p>
<p>Teraz budeme mať dve rôzne vzorky z dvoch distribúcií. A budeme testovať rozdiel ich stredných hodnôt. Najčastejšie testujeme, či je rozdiel nula alebo nie.</p>
<p>Uvažujme dve vzorky <span class="math inline">\(X_1, X_2, X_3, \dots, X_{n_{x}}\)</span> a <span class="math inline">\(Y_1, Y_2, Y_3, \dots Y_{n_{y}}\)</span>, veľkostí <span class="math inline">\(n_x\)</span> a <span class="math inline">\(n_y.\)</span></p>
<p>T-testy, ktoré tu prezentujeme sa dajú nahradiť Z-testami, v prípade, že je dátová vzorka dostatočne veľká je skreslenie minimálne.</p>
<section id="rovnaká-variancia" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="rovnaká-variancia"><span class="header-section-number">8.2.1</span> Rovnaká variancia</h3>
<p>Nech <span class="math display">\[X_1 \sim N(\mu_x,\sigma^2)\]</span> <span class="math display">\[Y_1 \sim N(\mu_y,\sigma^2)\]</span> a majme dve iid vzorky.</p>
<p>Ak majú spoločnú rovnakú varianciu, tak ju môžeme odhadnúť spolu <span class="math display">\[S^2 = \frac{(n_x-1)S^2_x + (n_y - 1)S^2_y}{(n_x-1) + (n_y-1)}\]</span> teda vážený priemer výberových variancií <span class="math inline">\(X\)</span> a <span class="math inline">\(Y.\)</span></p>
<p>Náhodná premenná</p>
<p><span class="math display">\[T \equiv \frac{(\bar{X} - \bar{Y}) - (\mu_x - \mu_y)}{S \sqrt{\frac{1}{n_x} + \frac{1}{n_y}}} \sim t_{n_x + n_y - 2}\]</span> Takže máme rozdelenie testovacej štatistiky.</p>
<div class="example" name="dojazd">
<p>Majú staršie auta iný diaľničný dojazd? Pozrime sa osobitne na diaľničný a mestský dojazd. Tu je syntax ako to urobíme v Rku.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mpg<span class="sc">$</span>hwy[mpg<span class="sc">$</span>year<span class="sc">&gt;=</span><span class="dv">2004</span>],mpg<span class="sc">$</span>hwy[mpg<span class="sc">$</span>year<span class="sc">&lt;</span><span class="dv">2004</span>],<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  mpg$hwy[mpg$year &gt;= 2004] and mpg$hwy[mpg$year &lt; 2004]
t = 0.032864, df = 232, p-value = 0.9738
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.511559  1.562841
sample estimates:
mean of x mean of y 
 23.45299  23.42735 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hwy <span class="sc">~</span> (year<span class="sc">&lt;</span><span class="dv">2004</span>), <span class="at">data=</span>mpg ,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  hwy by year &lt; 2004
t = 0.032864, df = 232, p-value = 0.9738
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -1.511559  1.562841
sample estimates:
mean in group FALSE  mean in group TRUE 
           23.45299            23.42735 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mpg<span class="sc">$</span>cty[mpg<span class="sc">$</span>year<span class="sc">&gt;=</span><span class="dv">2004</span>],mpg<span class="sc">$</span>cty[mpg<span class="sc">$</span>year<span class="sc">&lt;</span><span class="dv">2004</span>],<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  mpg$cty[mpg$year &gt;= 2004] and mpg$cty[mpg$year &lt; 2004]
t = -0.5675, df = 232, p-value = 0.5709
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.414159  0.781680
sample estimates:
mean of x mean of y 
 16.70085  17.01709 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cty <span class="sc">~</span> (year<span class="sc">&lt;</span><span class="dv">2004</span>), <span class="at">data=</span>mpg ,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  cty by year &lt; 2004
t = -0.5675, df = 232, p-value = 0.5709
alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
95 percent confidence interval:
 -1.414159  0.781680
sample estimates:
mean in group FALSE  mean in group TRUE 
           16.70085            17.01709 </code></pre>
</div>
</div>
<p>Nič tomu nenasvedčuje.</p>
<p>Ako to reportovať a zobraziť? Je užitočné tieto dáta aj zobraziť</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hwy <span class="sc">~</span> (year<span class="sc">&lt;</span><span class="dv">2004</span>), <span class="at">data=</span>mpg,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mpg<span class="sc">$</span>vek <span class="ot">&lt;-</span> <span class="fu">factor</span>(mpg<span class="sc">$</span>year<span class="sc">&lt;</span><span class="dv">2004</span>,<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"mladšie"</span>,<span class="st">"starśie"</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">753</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpg,<span class="fu">aes</span>(<span class="at">x=</span>vek,<span class="at">y=</span>hwy,<span class="at">fill=</span>vek)) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.shape =</span> <span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x=</span>vek,<span class="at">y=</span>hwy),</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span><span class="st">"grey60"</span>) <span class="sc">+</span> </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste0</span>(<span class="st">"Diaľničný dojazd (p = "</span>,</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.character</span>(<span class="fu">round</span>(t<span class="sc">$</span>p.value,<span class="dv">3</span>)),<span class="st">")"</span>),</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Dojazd"</span>,<span class="at">x =</span><span class="st">"Vek auta"</span>)<span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na základe dvojvýberového t-testu s rovnakými varianciami nevieme na hladine významnosti 5% zamietnuť, že priemerný diaľničný dojazd mladších aút je iný ako starších aút. Hodnota testovacej štatistiky je 0.032864 čomu zodpovedá p-hodnota 0.973.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>t2 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(cty <span class="sc">~</span> (year<span class="sc">&lt;</span><span class="dv">2004</span>), <span class="at">data=</span>mpg ,<span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">753</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>mpg,<span class="fu">aes</span>(<span class="at">x=</span>vek,<span class="at">y=</span>cty,<span class="at">fill=</span>vek)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.shape =</span> <span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x=</span>vek,<span class="at">y=</span>cty),</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span><span class="st">"grey60"</span>) <span class="sc">+</span> </span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste0</span>(<span class="st">"Dojazd v meste (p = "</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.character</span>(<span class="fu">round</span>(t2<span class="sc">$</span>p.value,<span class="dv">3</span>)),<span class="st">")"</span>),</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Dojazd"</span>,<span class="at">x =</span><span class="st">"Vek auta"</span>)<span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na základe dvojvýberového t-testu s rovnakými varianciami nevieme na hladine významnosti 5% zamietnuť, že priemerný dojazd v meste mladších aút je iný ako starších aút. Hodnota testovacej štatistiky je -0.5675 čomu zodpovedá p-hodnota 0.571.</p>
</div>
</section>
<section id="rôzna-variancia" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="rôzna-variancia"><span class="header-section-number">8.2.2</span> Rôzna variancia</h3>
<p>Nech <span class="math display">\[X_1 \sim N(\mu_x,\sigma_x^2)\]</span> <span class="math display">\[Y_1 \sim N(\mu_y,\sigma_y^2)\]</span> teda uvažujeme, že majú rôzne variancie.</p>
<p>Náhodná premenná</p>
<p><span class="math display">\[T \equiv \frac{(\bar{X} - \bar{Y}) - (\mu_x - \mu_y)}{\sqrt{\frac{s^2_x}{n_x} + \frac{s^2_y}{n_y}}} \sim t_{df}\]</span> má približné t-rozdelenie s</p>
<p><span class="math display">\[df = \frac{\left(\frac{s^2_x}{n_x}+\frac{s^2_y}{n_y} \right)^2}{\frac{\left(\frac{s^2_x}{n_x}\right)^2}{n_x-1} + \frac{\left(\frac{s^2_y}{n_y}\right)^2}{n_y-1}}.\]</span> stupňami voľnosti.</p>
<p>Testu založenému na tejto testovacej štatistike hovoríme <strong>Welchov test</strong>.</p>
<p><strong>Vybrať test s rovnakými varianciami alebo rôznymi varianciami?</strong></p>
<p>Záleží. Ak máme dobrý dôvod si myslieť, že variancie sú rovnaké, tak je rozumné túto informáciu využiť a použiť efektívnejší test, teda test, ktorý bude častejšie zamietať nesprávnu nulovú hypotézu. Na druhej strane ak nevieme, či sú variancie rovnaké, čo je v reálnych situáciách väčšinou, tak je lepšie a opatrnejšie použiť robustnejší test, ktorý umožňuje rôzne variancie. Áno, budeme menej efektívny v prípade, že variancie sú rovnaké ale aspoň nezaložíme naše testovanie na nepravdivej štatistike, ak by variancie boli nerovnaké. <strong>Väčšinou preto vyberáme Welchov test.</strong></p>
<p>Vráťme sa k dátam o výsledkoch testov.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2930</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>data_test8r <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">school=</span><span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"8r_gym"</span>, <span class="st">"4r_gym"</span>), <span class="at">each=</span><span class="dv">40</span>)),</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">score=</span><span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean=</span><span class="dv">75</span>, <span class="at">sd=</span><span class="dv">8</span>), <span class="fu">rnorm</span>(<span class="dv">40</span>, <span class="at">mean=</span><span class="dv">65</span>, <span class="at">sd=</span><span class="dv">5</span>)))</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>              )</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Pripomeňme si, že takto vyzerala ich distribúcia.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Znovu existujú dva rôzne spôsoby (syntaxe) ako spustiť tento test, ktoré dávajú identické výsledky.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(score <span class="sc">~</span> school, <span class="at">data=</span>data_test8r))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  score by school
t = -6.7799, df = 61.971, p-value = 5.173e-09
alternative hypothesis: true difference in means between group 4r_gym and group 8r_gym is not equal to 0
95 percent confidence interval:
 -12.074404  -6.575596
sample estimates:
mean in group 4r_gym mean in group 8r_gym 
              66.150               75.475 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data_test8r<span class="sc">$</span>score[data_test8r<span class="sc">$</span>school<span class="sc">==</span><span class="st">"4r_gym"</span>],data_test8r<span class="sc">$</span>score[data_test8r<span class="sc">$</span>school<span class="sc">==</span><span class="st">"8r_gym"</span>])</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  data_test8r$score[data_test8r$school == "4r_gym"] and data_test8r$score[data_test8r$school == "8r_gym"]
t = -6.7799, df = 61.971, p-value = 5.173e-09
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -12.074404  -6.575596
sample estimates:
mean of x mean of y 
   66.150    75.475 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">753</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>data_test8r,<span class="fu">aes</span>(<span class="at">x=</span>school,<span class="at">y=</span>score,<span class="at">fill=</span>school)) <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">outlier.shape =</span> <span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x=</span>school,<span class="at">y=</span>score),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">width=</span><span class="fl">0.2</span>,</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">color=</span><span class="st">"grey60"</span>) <span class="sc">+</span> </span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste0</span>(<span class="st">"Akademický výkon (p = "</span>,</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">as.character</span>(<span class="fu">round</span>(t_test<span class="sc">$</span>p.value,<span class="dv">3</span>)),<span class="st">")"</span>),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Score(points)"</span>,<span class="at">x =</span><span class="st">"Typ školy"</span>)<span class="sc">+</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na základe dvojvýberového t-testu s rôznymi varianciami (Welchov test) na hladine významnosti 5% zamietame, že priemerný výsledok na testoch 4ročných gymnázií je iný ako 8ročných gymnázií. Hodnota testovacej štatistiky je -6.78 čomu zodpovedá p-hodnota <span class="math inline">\(5.17 \cdot 10^{-9}\)</span>. Takže veľmi silne zamietame nulovú hypotézu, že sú tieto školy rovnaké, čo sa týka priemerných výsledkov testov.</p>
</section>
<section id="párové-testy" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="párové-testy"><span class="header-section-number">8.2.3</span> Párové testy</h3>
<p>Párový test nie je nič iné ako <a href="#jedno">jednovýberový test</a> aplikovaný na premennú <span class="math inline">\(X - Y,\)</span> keď <span class="math inline">\(n_x = n_y.\)</span> Príklad, ktorý sme v <a href="#jedno">sekcii</a> používali (zlepšenie) bol presne taký istý.</p>
<p>Párový test so sebou nesie samozrejme viacej informácie ako obyčajný (nepárový) dvojvýberový test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(test <span class="sc">~</span> cas, <span class="at">data=</span>data_test, <span class="at">mu=</span><span class="dv">15</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  test by cas
t = 1.5229, df = 42.651, p-value = 0.1352
alternative hypothesis: true difference in means between group po and group pred is not equal to 15
95 percent confidence interval:
 13.94414 22.56190
sample estimates:
  mean in group po mean in group pred 
          64.87932           46.62629 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test(test ~ cas, paired=TRUE,data=data_test, mu=15)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data_test<span class="sc">$</span>test[data_test<span class="sc">$</span>cas<span class="sc">==</span><span class="st">"pred"</span>],data_test<span class="sc">$</span>test[data_test<span class="sc">$</span>cas<span class="sc">==</span><span class="st">"po"</span>], <span class="at">paired=</span><span class="cn">TRUE</span>,<span class="at">data=</span>data_test, <span class="at">mu=</span><span class="dv">15</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  data_test$test[data_test$cas == "pred"] and data_test$test[data_test$cas == "po"]
t = -14.65, df = 29, p-value = 6.17e-15
alternative hypothesis: true mean difference is not equal to 15
95 percent confidence interval:
 -22.89547 -13.61057
sample estimates:
mean difference 
      -18.25302 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(zmena, <span class="at">mu=</span><span class="dv">15</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  zmena
t = 1.4331, df = 29, p-value = 0.1625
alternative hypothesis: true mean is not equal to 15
95 percent confidence interval:
 13.61057 22.89547
sample estimates:
mean of x 
 18.25302 </code></pre>
</div>
</div>
<p>Obyčajný nepárový test ignoruje informáciu, že dané testy boli písané tými istými ľuďmi.</p>
<p>Pozrime sa na klasický prípad Studenta, podľa, ktorého je t-test označovaný aj ako Studentov t-test. Zaoberal sa o koľko viacej ľudia spali keď užívali rôzne lieky.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  sleep$extra[sleep$group == 1] and sleep$extra[sleep$group == 2]
t = -4.0621, df = 9, p-value = 0.002833
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.4598858 -0.7001142
sample estimates:
mean difference 
          -1.58 </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na základe párového t-testu na hladine významnosti 5% zamietame, že priemerné predĺženie spánku je rovnaké pri užívaní rôznych liekov. Hodnota testovacej štatistiky je -4.062 čomu zodpovedá p-hodnota 0.0028. Všimnime si, že teraz dáva zmysel spojiť jednotlivé merania toho istého subjektu čiarou - párový test totiž berie túto informáciu do úvahy.</p>
<p>Poznamenajme, že ak by sme ignorovali informáciu, že ide o párové dáta, na hladine významnosti 5% by sme ju ani nevedeli zamietnuť(!)</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  extra by group
t = -1.8608, df = 17.776, p-value = 0.07939
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -3.3654832  0.2054832
sample estimates:
mean in group 1 mean in group 2 
           0.75            2.33 </code></pre>
</div>
</div>
</section>
</section>
<section id="porovnanie-stredných-hodnôt-viacerých-vzoriek-anova" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="porovnanie-stredných-hodnôt-viacerých-vzoriek-anova"><span class="header-section-number">8.3</span> Porovnanie stredných hodnôt viacerých vzoriek (ANOVA)</h2>
<p>Môžeme chcieť otestovať rovnosť stredných hodnôt vo viacerých ako v dvoch skupinách. Napríklad ak by sme testovali ako dobre fungujú 4 rôzne liečby.</p>
<p>Za týmto účelom používame test ANOVA (analysis of variance). Jeho predpokladmi sú rovnaké variancie, normalita a nezávislosť vzoriek.</p>
<p>Majte teraz <span class="math inline">\(k\)</span> rôznych skupín s veľkosťami dátových vzoriek <span class="math inline">\(n_1, n_2, \cdots n_k\)</span>. Nulová hypotéza, ktorá nás zaujíma je <span class="math display">\[H_0: \mu_{Y_1} = \mu_{Y_2} = \cdots \mu_{Y_k}\]</span> Testovacia štatistika má nasledovný tvar:</p>
<p><span class="math display">\[F = \sum_{j=1}^k n_j \frac{(\bar Y_{j} - \bar{Y})^2}{k-1} \sim F_{k-1,n-k}\]</span> kde <span class="math inline">\(n = n_1 + \cdots n_k\)</span> a <span class="math inline">\(\bar{Y}\)</span> je celkový priemer.</p>
<p>Tu je implementácia testu, kde sa pozeráme, či je diaľničný dojazd rôzny cez rôzne kategórie aút (7 kategórií: minivan, compact, subcompact, midsize, suv, 2seater, pickup).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">aov</span>(hwy <span class="sc">~</span> class, <span class="at">data =</span> mpg)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_model)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
class         6   5683   947.2   83.39 &lt;2e-16 ***
Residuals   227   2578    11.4                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>P-hodnota testu je veľmi malá a zamietame nulovú hypotézu, že rôzne kategórie áut majú rovnaký priemerný diaľničný dojazd (čo zasa asi nie je až také prekvapivé).</p>
</section>
<section id="konfidenčný-interval" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="konfidenčný-interval"><span class="header-section-number">8.4</span> Konfidenčný interval</h2>
<p>Doteraz sme používali p-hodnotu na kvantifikáciu toho, ako veľmi je nulová hypotéza kompatibilná s našou dátovou vzorkou. Iný, alternatívny pohľad na kvantifikovanie neistoty je pozrieť sa na množinu všetkých tých hodnôt, ktoré by neboli bývali zamietnuté pri nejakej fixnej hladine významnosti.</p>
<p>Vezmime si napríklad jednovýberový T-test. T-štatistika <span class="math inline">\(T \equiv \sqrt{n}\frac{\bar{X}_n - \mu}{S}\)</span> má <span class="math inline">\(t_{n-1}\)</span> rozdelenie, takže</p>
<p><span class="math display">\[P\left(t^{(\alpha/2)}_{n-1} \leq T \leq t^{(1-\alpha/2)}_{n-1}\right) = P\left(t^{(\alpha/2)}_{n-1} \leq \sqrt{n}\frac{\bar{X}_n - \mu}{S} \leq t^{(1-\alpha/2)}_{n-1}\right) = 1-\alpha,\]</span> kde <span class="math inline">\(t^{(\alpha)}_{n-1}\)</span> označuje <span class="math inline">\(100(\alpha/2)\%\)</span>-ný kvantil T-rozdelenia s <span class="math inline">\(n-1\)</span> stupňami voľnosti. Nakoľko je T-rozdelenie symetrické, máme <span class="math inline">\(t^{(\alpha/2)}_{n-1} = - t^{(1-\alpha/2)}_{n-1}.\)</span> Teda:</p>
<p><span class="math display">\[P\left(-t^{(1-\alpha/2)}_{n-1} \leq \sqrt{n}\frac{\bar{X}_n - \mu}{S} \leq t^{(1-\alpha/2)}_{n-1}\right) = 1-\alpha,\]</span> Ak je naša dátová vzorka veľkosti <span class="math inline">\(n=10\)</span>, a hladina významnosti <span class="math inline">\(5\%\)</span> potom máme <span class="math inline">\(t_9^{0.975} = 2.262.\)</span></p>
<p>Nulovú hypotézu zamietame vždy ak <span class="math inline">\(\bar{X}_n &gt; \mu + t^{(1-\alpha/2)}_{n-1} \frac{S}{\sqrt{n}}\)</span> alebo <span class="math inline">\(\bar{X}_n &lt; \mu - t^{(1-\alpha/2)}_{n-1} \frac{S}{\sqrt{n}}.\)</span> Nižšie sú zobrazené hodnoty <span class="math inline">\(t^{(0.025)}_{9}\)</span> a <span class="math inline">\(t^{(0.975)}_{9},\)</span> súčet obsahov týchto dvoch modrých plôch dáva <span class="math inline">\(0.05\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Teraz môžeme zadefinovať <span class="math inline">\((1-\alpha)100\%\)</span>ný <strong>konfidenčný interval</strong> pre odhad strednej hodnoty ako množinu všetkých parametrov <span class="math inline">\(\mu\)</span>, ktoré by neboli zamietnuté štatistickým testom na hladine významnosti <span class="math inline">\(\alpha.\)</span></p>
<p><span class="math display">\[CI^{(1-\alpha)} = \left[\bar{X}_n - t^{(1-\alpha/2)}_{n-1} \frac{S}{\sqrt{n}},\bar{X}_n + t^{(1-\alpha/2)}_{n-1} \frac{S}{\sqrt{n}} \right].\]</span></p>
<p>Je dôležité si uvedomiť, že konfidenčný interval je <strong>náhodný interval</strong>. Náhodnosť plynie z <span class="math inline">\(\bar{X}_n\)</span> a <span class="math inline">\(S\)</span>, ktoré sú <strong>náhodné</strong> premenné. To znamená, že jedna dátová vzorka nám dá len jednu realizáciu <span class="math inline">\(CI^{(1-\alpha)}.\)</span> Jeho interpretácia je taká, že ak by sme dostali 100 náhodných vzoriek z modelu, tak tento náhodný interval by ho pokryl približne 5 krát.</p>
<p>Pozrime sa na to na nasledujúcej simulácii (ktorú si urobíme ako cvičenie):</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pozorujeme, že spomedzi 100 simulácií <span class="math inline">\(95\%\)</span>ný konfidenčný interval pokryl skutočnú hodnotu 94 krát, zatiaľčo <span class="math inline">\(90\%\)</span>ný konfidenčný interval pokryl túto hodnotu 89 krát. Ak by sme mali týcho simulácii viacej, tento pomer by sa blížil k <span class="math inline">\(95\%\)</span> a <span class="math inline">\(90\%\)</span>.</p>
</section>
<section id="testovanie-podielu" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="testovanie-podielu"><span class="header-section-number">8.5</span> Testovanie podielu</h2>
<p>Niekedy sme v situácii, že potrebujeme skúmať rozdiely medzi skupinami a premenná, ktorú sledujeme je binárna - áno/nie.</p>
<ul>
<li>Niečo nastalo/nenastalo</li>
<li>Produkt bol zakúpený</li>
<li>Pacient sa vyzdravil do 2 týždňov</li>
</ul>
<section id="testovanie-podielu-pre-jednu-skupinu" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="testovanie-podielu-pre-jednu-skupinu"><span class="header-section-number">8.5.1</span> Testovanie podielu pre jednu skupinu</h3>
<p>Predstavme si nasledovnú situáciu. Zo vzorky <span class="math inline">\(n=1024\)</span> respondentov získa v prieskume volebných preferencií určitá strana <span class="math inline">\(6.152\%\)</span> (63 hlasov). Zaujíma ju, či sa dostane do parlamentu, teda, či prekročí hranicu <span class="math inline">\(5\%\)</span>.</p>
<p>Uvažujme, že počet respondentov, ktorí odpovedali, že by ju volili je rozdelený binomicky s neznámou pravdepodobnosťou <span class="math inline">\(p\)</span>:</p>
<p><span class="math display">\[Y \sim Bin(n,p)\]</span>.</p>
<p>Akonáhle je <span class="math inline">\(n\)</span> dostatočne veľké, tak máme</p>
<p><span class="math display">\[Z \equiv \frac{Y - np}{\sqrt{n p (1-p)}} \rightarrow_D N(0,1).\]</span></p>
<p>Toto platí kvôli Zákonu o veľkých číslach (<span class="math inline">\(Y = X_1 + \dots + X_n,\)</span> kde <span class="math inline">\(X_i \sim Bern(p)\)</span>) a skutočnosti, že <span class="math inline">\(\text{E}[Y] = np\)</span> a <span class="math inline">\(\text{Var}[Y] = np(1-p).\)</span></p>
<p>V našom prípade</p>
<p><span class="math display">\[\frac{53 - 51.2}{\sqrt{1024 \cdot 0.05 \cdot 0.95}} \approx 1.692\]</span> Porovnáme túto hodnotu s <span class="math inline">\(95\%\)</span>ným kvantilom normálneho rozdelenia, ktorý je 1.645, takže zamietli by sme nulovú hypotézu toho, že <span class="math inline">\(p=0.05\)</span> v prospech jednostrannej hypotézy, že <span class="math inline">\(p&gt;0.05\)</span> na hladine významnosti <span class="math inline">\(5\%.\)</span></p>
<p>Ako vyzerá <strong>obojstranný</strong> konfidenčný interval?</p>
<p><span class="math display">\[P\left(-z^{(1-\alpha/2)} \leq Z \leq z^{(1-\alpha/2)}_{n-1}\right) = P\left(-z^{(1-\alpha/2)} \leq \frac{Y - np}{\sqrt{n p (1-p)}}  \leq z^{(1-\alpha/2)}\right) \approx 1-\alpha,\]</span> Teraz z praktických dôvodov nahradíme neznáme <span class="math inline">\(p\)</span> v menovateli jeho odhadom <span class="math inline">\(\hat p = Y/n\)</span> (v našom prípade <span class="math inline">\(6.152\%\)</span>) Aproximatívna rovnosť <span class="math inline">\(\approx\)</span> teraz bude mať dva zdroje chyby - <span class="math inline">\(\frac{Y - np}{\sqrt{n p (1-p)}}\)</span> je totiž len približne normálne rozdelené a naviac menovateľ <span class="math inline">\(\sqrt{n \hat p (1- \hat p)}\)</span> je len približne smerodajnou odchýlkou <span class="math inline">\(Y.\)</span></p>
<p><span class="math display">\[P\left(-z^{(1-\alpha/2)} \leq \frac{Y - np}{\sqrt{n \hat p (1- \hat p)}}  \leq z^{(1-\alpha/2)}\right) \approx 1-\alpha.\]</span></p>
<p>V tejto zátvorke potrebuje popreusporiadať objekty tak, aby sme osamostatnili <span class="math inline">\(p\)</span>.</p>
<span class="math display">\[\begin{eqnarray*}

P\left(-z^{(1-\alpha/2)} \leq \frac{Y - np}{\sqrt{n \hat p (1- \hat p)}}  \leq z^{(1-\alpha/2)}\right) &amp;=&amp; 1-\alpha, \\
P\left(-z^{(1-\alpha/2)}\sqrt{n \hat p (1- \hat p)} \leq  Y - np \leq z^{(1-\alpha/2)}\sqrt{n \hat p (1- \hat p)}\right) &amp;=&amp; 1-\alpha, \\
P\left(Y + z^{(1-\alpha/2)}\sqrt{n \hat p (1- \hat p)} \geq  np  \geq Y - z^{(1-\alpha/2)}\sqrt{n \hat p (1- \hat p)}\right) &amp;=&amp; 1-\alpha,\\
P\left(\frac{Y}{n} + z^{(1-\alpha/2)}\sqrt{\frac{1}{n} \hat p (1- \hat p)} \geq  p  \geq \frac{Y}{n} - z^{(1-\alpha/2)}\sqrt{\frac{1}{n} \hat p (1- \hat p)}\right) &amp;=&amp; 1-\alpha,\\
P\left(\hat p - z^{(1-\alpha/2)}\sqrt{\frac{1}{n} \hat p (1- \hat p)} \leq  p  \leq \hat p + z^{(1-\alpha/2)}\sqrt{\frac{1}{n} \hat p (1- \hat p)}\right) &amp;=&amp; 1-\alpha,
\end{eqnarray*}\]</span>
<p>Takže konfidenčný interval dostávame nasledovný:</p>
<p><span class="math display">\[CI^{(1-\alpha)} = \left[\hat p - z^{(1-\alpha/2)}\sqrt{\frac{\hat p (1- \hat p)}{n}},\hat p + z^{(1-\alpha/2)}\sqrt{\frac{\hat p (1- \hat p)}{n} } \right].\]</span> Pozrime sa na nasledovnú <a href="https://www.focus-research.sk/wp-content/uploads/2022/03/Volebne-preferencie-politickych-stran-februar-2022.pdf">tlačovú správu o volebnom prieskume</a> jednej slovenskej prieskumnej agentúry.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_focus.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Prieskum volebných preferencií z februára 2022.</figcaption>
</figure>
</div>
</div>
</div>
<p>Poďme sa pozrieť hneď na prvý riadok. Z 1003 respondentov <span class="math inline">\(65.2\%\)</span> respondentov označilo stranu, to jest 654. Z nich <span class="math inline">\(18.5\%\)</span> zodpovedá 121 respondentov. <span class="math inline">\(95\%\)</span>ný interval spoľahlivosti je preto:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>hatp <span class="ot">&lt;-</span> <span class="dv">121</span><span class="sc">/</span><span class="dv">654</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>c_low  <span class="ot">&lt;-</span> hatp <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">sqrt</span>(hatp<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>hatp)<span class="sc">/</span><span class="dv">654</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>c_high <span class="ot">&lt;-</span> hatp <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)<span class="sc">*</span><span class="fu">sqrt</span>(hatp<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>hatp)<span class="sc">/</span><span class="dv">654</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(c_low, c_high),<span class="dv">3</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.155 0.215</code></pre>
</div>
</div>
<p>Test, ktorý berie do úvahy skutočnosť, že binomicky rozdelená premenná nie je spojitá, je implementovaný pomocou</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">121</span>,<span class="dv">654</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test with continuity correction

data:  121 out of 654, null probability 0.5
X-squared = 258.29, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.1564114 0.2173919
sample estimates:
        p 
0.1850153 </code></pre>
</div>
</div>
<p>a verzia vhodná na malé dátové vzorky (presný test)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">121</span>,<span class="dv">654</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  121 and 654
number of successes = 121, number of trials = 654, p-value &lt; 2.2e-16
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.1559671 0.2169387
sample estimates:
probability of success 
             0.1850153 </code></pre>
</div>
</div>
<p>Z praktického hľadiska medzi nimi väčšinou nie je veľký rozdiel. Extenzívne porovnanie kvality rôznych testov je napríklad <a href="https://doi.org/10.1002/(SICI)1097-0258(19980430)17:8%3C857::AID-SIM777%3E3.0.CO;2-E">tu</a>.</p>
<p>Poďme sa bližšie pozrieť pod kapotu <code>prop.test</code> s parametrom <code>correct=FALSE</code>. Budeme mechanicky meniť pravdepodobnosť testu a ukladať si p-hodnotu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">121</span>,<span class="dv">654</span>,<span class="at">p=</span><span class="fl">0.2</span>,<span class="at">correct=</span><span class="cn">FALSE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test without continuity correction

data:  121 out of 654, null probability 0.2
X-squared = 0.91781, df = 1, p-value = 0.338
alternative hypothesis: true p is not equal to 0.2
95 percent confidence interval:
 0.1571244 0.2165849
sample estimates:
        p 
0.1850153 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> (<span class="dv">121</span> <span class="sc">-</span> <span class="dv">654</span><span class="sc">*</span><span class="fl">0.2</span>)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">654</span><span class="sc">*</span><span class="fl">0.2</span><span class="sc">*</span>(<span class="dv">1</span><span class="fl">-0.2</span>))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(U)))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3380497</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">121</span>,<span class="dv">654</span>,<span class="at">correct=</span><span class="cn">FALSE</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test without continuity correction

data:  121 out of 654, null probability 0.5
X-squared = 259.55, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.1571244 0.2165849
sample estimates:
        p 
0.1850153 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>p_vec <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.14</span>,<span class="fl">0.22</span>,<span class="at">by=</span><span class="fl">0.00001</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>np <span class="ot">&lt;-</span> <span class="fu">length</span>(p_vec)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>pval_vec <span class="ot">&lt;-</span> <span class="fu">numeric</span>(np)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (ip <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>np){</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  pval_vec[ip] <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="dv">121</span>,<span class="dv">654</span>,<span class="at">p=</span>p_vec[ip],<span class="at">correct=</span><span class="cn">FALSE</span>)<span class="sc">$</span>p.value</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(p_vec[<span class="fu">which</span>(pval_vec<span class="sc">&gt;</span><span class="fl">0.05</span>)])</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.15713 0.21658</code></pre>
</div>
</div>
<p>Teraz vidíme, že funkcia <code>prop.test</code> implementuje nasledovný konfidenčný interval,</p>
<p><span class="math display">\[P\left(-z^{(1-\alpha/2)} \leq \frac{Y - np}{\sqrt{n  p (1- p)}}  \leq z^{(1-\alpha/2)}\right) \approx 1-\alpha,\]</span> rozdielom je, že v menovateli nie je aproximácia.</p>
<p>A teraz sa pozrime na exaktný test <code>binom.test</code>. Tento test nerobí vôbec žiadnu aproximáciu normálnym rozdelením.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># exact - based on binomial distribution</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">121</span>,<span class="dv">654</span>,<span class="fl">0.2</span>,<span class="at">alternative=</span><span class="st">"two.sided"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  121 and 654
number of successes = 121, number of trials = 654, p-value = 0.3533
alternative hypothesis: true probability of success is not equal to 0.2
95 percent confidence interval:
 0.1559671 0.2169387
sample estimates:
probability of success 
             0.1850153 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#more extreme number than 121?</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">80</span><span class="sc">:</span><span class="dv">170</span>,<span class="fu">dbinom</span>(<span class="dv">80</span><span class="sc">:</span><span class="dv">170</span>, <span class="dv">654</span>, <span class="at">p=</span><span class="fl">0.2</span>))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">121</span>,<span class="fu">dbinom</span>(<span class="dv">121</span>, <span class="dv">654</span>, <span class="at">p=</span><span class="fl">0.2</span>),<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">dbinom</span>(<span class="dv">121</span>, <span class="dv">654</span>, <span class="at">p=</span><span class="fl">0.2</span>),<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">80</span><span class="sc">:</span><span class="dv">121</span>,<span class="fu">dbinom</span>(<span class="dv">80</span><span class="sc">:</span><span class="dv">121</span>, <span class="dv">654</span>, <span class="at">p=</span><span class="fl">0.2</span>),<span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">141</span><span class="sc">:</span><span class="dv">170</span>,<span class="fu">dbinom</span>(<span class="dv">141</span><span class="sc">:</span><span class="dv">170</span>, <span class="dv">654</span>, <span class="at">p=</span><span class="fl">0.2</span>),<span class="at">col=</span><span class="st">"green"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">121</span>,<span class="dv">654</span>,<span class="fl">0.2</span>))<span class="sc">+</span><span class="fu">sum</span>(<span class="fu">dbinom</span>(<span class="dv">141</span><span class="sc">:</span><span class="dv">654</span>,<span class="dv">654</span>,<span class="fl">0.2</span>))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3532905</code></pre>
</div>
</div>
<p>Za predpokladu nulovej hypotézy priamo vieme rozdelenie. Sčítame pravdepodobnosti ešte extrémnejšej udalosti.</p>
</section>
<section id="testovanie-rovnosti-podielov-pre-dve-skupiny" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="testovanie-rovnosti-podielov-pre-dve-skupiny"><span class="header-section-number">8.5.2</span> Testovanie rovnosti podielov pre dve skupiny</h3>
<p>Testovacia štatistika, ktorá testuje nulovú hypotézu, že proporcie v dvoch vzorkách veľkosti <span class="math inline">\(n_1\)</span> a <span class="math inline">\(n_2\)</span> sú rovnaké, má nasledovnú formu:</p>
<p><span class="math display">\[Z \equiv \frac{\hat p_1 - \hat p_2 }{\sqrt{ \hat p (1 - \hat p) \left(\frac{1}{n_1} + \frac{1}{n_2}\right) }} \rightarrow_D N(0,1),\]</span></p>
<p>kde <span class="math inline">\(\hat p_1 = Y_1/n_1, \hat p_2 = Y_2/n_2, \hat p = \frac{Y_1 + Y_2}{n_1 + n_2}.\)</span></p>
<div class="example">
<p>Chceli by sme porovnať efekt dvoch jedov na hmyz. V prvej skupine sme namerali, že 28 z 90 hmyzov zahynulo. V druhej skupine to bolo 8 zo 60. Hodnota <span class="math inline">\(Z\)</span> štatistiky je</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>hatp1 <span class="ot">&lt;-</span> <span class="dv">28</span><span class="sc">/</span><span class="dv">90</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>hatp2 <span class="ot">&lt;-</span> <span class="dv">8</span><span class="sc">/</span><span class="dv">60</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>hatp <span class="ot">&lt;-</span> (<span class="dv">28</span><span class="sc">+</span><span class="dv">8</span>)<span class="sc">/</span>(<span class="dv">90</span><span class="sc">+</span><span class="dv">60</span>)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>( Z <span class="ot">&lt;-</span> (hatp1<span class="sc">-</span>hatp2)<span class="sc">/</span><span class="fu">sqrt</span>(hatp<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>hatp)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">90</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">60</span>)) )</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.497562</code></pre>
</div>
</div>
<p>a kritická hodnota obojstranného 95<span class="math inline">\(\%\)</span> testu je</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p>takže zamietame nulovú hypotézu, že dva insekticídy sú rovnaké. P-hodnota obojstranného testu je</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(Z)))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01250505</code></pre>
</div>
</div>
<p>Iný spôsob na základe inej testovacej štatistiky s korekciou na spojitosť je</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(<span class="dv">28</span>,<span class="dv">8</span>),<span class="fu">c</span>(<span class="dv">90</span>,<span class="dv">60</span>))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(28, 8) out of c(90, 60)
X-squared = 5.3012, df = 1, p-value = 0.02131
alternative hypothesis: two.sided
95 percent confidence interval:
 0.03525685 0.32029870
sample estimates:
   prop 1    prop 2 
0.3111111 0.1333333 </code></pre>
</div>
</div>
</div>
</section>
</section>
<section id="kontigenčné-tabuľky" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="kontigenčné-tabuľky"><span class="header-section-number">8.6</span> Kontigenčné tabuľky</h2>
<p>Začnime príkladom. Chceli by sme vedieť či súvisí farba očí s farbou vlasov. Máme odpozorovanú vzorku 592 ĺudí v rôznych kategóriách. Neexistuje žiadne prirodzené číselné usporiadanie farieb, ide o <strong>kategorickú</strong> premennú.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Vidíme, že máme 20 modrokých ľudí s čiernymi vlasmi ale 68 ľudí s hnedými očami (20 ľudí má orieškovú farbu očí - pozn. ja som tie farby nevymýšľal.).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Modrookých a hnedookých ľudí je podobne veľa, okolo 37<span class="math inline">\(\%\)</span>. Predstavme si teraz situáciu, že vieme, len proporcie po stĺpcoch, že nevieme aká je súvzťažnosť medzi farbou očí a vlasov.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Ak, by bola farba vlasov a očí nezávislá, potom by sme vedeli aká je proporcia jednotlivých kombinácií. Napríklad hnedovlasých ľudí s orieškovými očami by malo byť <span class="math inline">\(0.483*0.157=0.0759.\)</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Takže by sme očakávali, že za predpokladu <strong>nezávislosti</strong> by ich malo byť zhruba <span class="math inline">\(44.9\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Teraz môžeme testovaciu štatistiku založiť na tom, že očakávaná tabuľka za predpokladu nezávislosti by mala byť blízka tej pozorovanej. Ak budú rozdiely veľmi veľké, zamietame nulovú hypotézu nezávislosti.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig_7_ind6.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Testovacia štatistika má nasledovnú formu:</p>
<p><span class="math display">\[ C = \sum_i \frac{(O_i - E_i)^2}{E_i} \sim \chi^2_{m}, \]</span> kde</p>
<ul>
<li><span class="math inline">\(i\)</span> je skupina (napríklad kombinácia farby vlasov a očí)</li>
<li><span class="math inline">\(O_i\)</span> je počet pozorovaní v skupine <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(E_i\)</span> je počet očakávaných pozorovaní v skupine <span class="math inline">\(i\)</span> za platnosti nezávislosti</li>
<li><span class="math inline">\(m\)</span> označuje počet stupňov voľnosti. Je to <span class="math inline">\(m = (c_1 - 1)(c_2-1)\)</span> kde <span class="math inline">\(c_1\)</span> je počet kategórii prvej kategorickej premennej a <span class="math inline">\(c_2\)</span> je počet kategórii druhej kategorickej premennej. (V našom prípade <span class="math inline">\(c_1 = c_2 = 4\)</span> a preto <span class="math inline">\(m = (4-1)(4-1)=9.\)</span>)</li>
</ul>
<p>Tu je mechanická implementácia v R ako aj výsledok za použitia funkcie <code>chisq.test</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>haireye</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     y   eye  hair
1    5 green BLACK
2   29 green BROWN
3   14 green   RED
4   16 green BLOND
5   15 hazel BLACK
6   54 hazel BROWN
7   14 hazel   RED
8   10 hazel BLOND
9   20  blue BLACK
10  84  blue BROWN
11  17  blue   RED
12  94  blue BLOND
13  68 brown BLACK
14 119 brown BROWN
15  26 brown   RED
16   7 brown BLOND</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>(ct <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(y <span class="sc">~</span> hair <span class="sc">+</span> eye, haireye))</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       eye
hair    green hazel blue brown
  BLACK     5    15   20    68
  BROWN    29    54   84   119
  RED      14    14   17    26
  BLOND    16    10   94     7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ct)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: xtabs(formula = y ~ hair + eye, data = haireye)
Number of cases in table: 592 
Number of factors: 2 
Test for independence of all factors:
    Chisq = 138.29, df = 9, p-value = 2.325e-25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">250</span>,<span class="fu">dchisq</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">250</span>,<span class="at">df=</span><span class="dv">9</span>),<span class="at">type=</span><span class="st">"l"</span>)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(ct,<span class="dv">1</span>)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">margin.table</span>(ct,<span class="dv">1</span>))</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">margin.table</span>(ct,<span class="dv">2</span>)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">margin.table</span>(ct,<span class="dv">2</span>))</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co">#table under independency</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>indTable <span class="ot">&lt;-</span> h <span class="sc">%*%</span> <span class="fu">t</span>(e)</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(indTable)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">sum</span>(ct)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( (ct <span class="sc">-</span> indTable<span class="sc">*</span>N)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(indTable<span class="sc">*</span>N) ) </span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 138.2898</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(ct)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ttest_files/figure-html/ttest-45-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(ct)</span></code><button title="Kopírovať do schránky" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  ct
X-squared = 138.29, df = 9, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Je neprekvapivé, že v tomto prípade veľmi silno zamietame nulovú hypotézu o tom, že farba očí a vlasov je nezávislá.</p>
</section>
<section id="zopár-poznámok-na-záver." class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="zopár-poznámok-na-záver."><span class="header-section-number">8.7</span> Zopár poznámok na záver.</h2>
<ul>
<li>V praxi je užitočné zobraziť dáta. Vždy.</li>
<li>V drvivej väčšine prípadov robíme test s nerovnakými varianciami. Málokedy máme dôvod uvažovať, že vzorky majú rovnakú varianciu.</li>
<li>Na to, ako veĺmi popisuje normálne rozdelenie naše vzorky môžeme pomôcť vizualizačné nástroje. Ak aj nie sú normálne, vďaka centrálnej limitnej vete budú pre rastúcu dátovú vzorku naše štatistiky aspoň asymptoticky t alebo normálne rozdelené.</li>
<li>Na veľmi malé dátové vzorky sa niekedy používajú aj neparametrické testy. Tieto nespomíname v tomto kurze.</li>
<li>Je zvyklosťou používať hladinu významnosti 5%. Ale to je všetko, je to zvyk. Nie sú žiadne teoretické dôvody, prečo je toto menej vhodné číslo ako 1% alebo 11.343%.</li>
<li>P-hodnoty sú <a href="https://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1154108#.Y2jv-S8w1qu">častokrát dezinterpretované</a>. P-hodnota hovorí, že
<ul>
<li>za platnosti nulovej hypotézy (napríklad <span class="math inline">\(\mu=3\)</span>)</li>
<li>za platnosti modelových predpokladov (napr. rovnaká variancia)</li>
<li>aká by bola šanca, že uvidíme ešte extrémnejší výsledok ako ten čo pozorujeme, ak by sme opakovali zber dát mnohokrát. No ale toto je problém lebo my máme <strong>len jednu vzorku</strong>.</li>
</ul></li>
<li>Okrem štatistickej významnosti sa treba pozerať aj na reálnu hodnotu rozdielu. Ak budeme mať dostatočne veľa dát, tak <strong>vždy</strong> zamietneme nulovú hypotézu, že stredné hodnoty dvoch vzoriek sú rovnaké. Ale ak je rozdiel v dojazde na nádrž auta 0.3km alebo ak je rozdiel v ročnej mzde 4.50eur, tak tento hoc aj štatisticky významný rozdiel nie je zaujímavý.</li>
<li>Existuje dosť veľká skupina ľudí, ktorá považuje tento spôsob uvažovania (štatistické testovanie hypotéz) za <a href="https://www.nature.com/articles/519009f">neužitočný</a>. (Toto môžeme byť aj my ale najprv tomu budeme musieť do hĺbky porozumieť)</li>
<li>Štatistické testovanie hypotéz môže vzbudiť dojem vedeckosti. Nie je však o nič vedeckejšie ako zobraziť dáta vhodnou vizualizáciou. Na testovanie sa pozeráme ako na ďalší nástroj, ktorého ambíciou je byť užitočné. To, že niečo zamietneme alebo nezamietneme neznamená, že to je alebo nie je pravda. Testovanie nám umožňuje systematizovať naše rozhodovanie a kvantifikovať intuíciu, ktorú nadobudneme pozeraním sa na surové dáta.</li>
</ul>
</section>
<section id="prehľad" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="prehľad"><span class="header-section-number">8.8</span> Prehľad</h2>
<div style="font-size: 0.7em;">
<div style="overflow-x: auto; width: 100%;">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Použitie</th>
<th>Test</th>
<th>Testovacia štatistika</th>
<th>Hypotéza</th>
<th>V Rku</th>
<th>Poznámky</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stredná hodnota je rovná číslu <span class="math inline">\(\mu\)</span></td>
<td>Z-Test</td>
<td>(Z= N(0,1))</td>
<td>(H_0): <span class="math inline">\(\mu_X = \mu\)</span></td>
<td><code>BSDA::z.test()</code></td>
<td>Vyžaduje známe <span class="math inline">\(\sigma\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>T-Test</td>
<td>(T= t_{n})</td>
<td>(H_0): <span class="math inline">\(\mu_X = \mu\)</span></td>
<td><code>t.test()</code></td>
<td>Používa odhadnuté <span class="math inline">\(\sigma\)</span></td>
</tr>
<tr class="odd">
<td>Porovnanie stredných hodnôt dvoch vzoriek</td>
<td>T-Test</td>
<td>(T t_{n_x + n_y - 2})</td>
<td>(H_0): <span class="math inline">\(\mu_X = \mu_Y\)</span></td>
<td><code>t.test(,var.equal=TRUE)</code></td>
<td>(S) je odhadom (_X = _Y)</td>
</tr>
<tr class="even">
<td></td>
<td>(Welchov) T-Test</td>
<td>(T t_{df})</td>
<td>(H_0): <span class="math inline">\(\mu_X = \mu_Y\)</span></td>
<td><code>t.test(,var.equal=FALSE)</code></td>
<td>Približný test</td>
</tr>
<tr class="odd">
<td></td>
<td>Párový T-Test</td>
<td>(T t_{n-1})</td>
<td>(H_0): <span class="math inline">\(\mu_X - \mu_Y = 0\)</span></td>
<td><code>t.test(,paired=TRUE)</code></td>
<td>(n_X = n_Y)</td>
</tr>
<tr class="even">
<td>Porovnanie stredných hodnôt viacerých vzoriek</td>
<td>ANOVA</td>
<td>(F = *{j=1}^k n_j* F{k-1,n-k})</td>
<td>(H_0): <span class="math inline">\(\mu_{Y_1} = \mu_{Y_2} = \cdots \mu_{Y_k}\)</span></td>
<td><code>aov()</code></td>
<td></td>
</tr>
<tr class="odd">
<td>Testovanie podielu pre jednu skupinu</td>
<td>Z-test</td>
<td>(Z _D N(0,1) )</td>
<td>(H_0): <span class="math inline">\(p_Y = p\)</span></td>
<td><code>z.test()</code></td>
<td>Veľká vzorka</td>
</tr>
<tr class="even">
<td></td>
<td>Chí-Kvadrát test</td>
<td>(^2_1 )</td>
<td>(H_0): <span class="math inline">\(p_Y = p\)</span></td>
<td><code>prop.test()</code></td>
<td>Na základe kont. tabuľky</td>
</tr>
<tr class="odd">
<td></td>
<td>Binomický test</td>
<td>(Y Binom(n,p) )</td>
<td>(H_0): <span class="math inline">\(p_Y = p\)</span></td>
<td><code>binom.test()</code></td>
<td>Exaktný test - pre malé vzorky</td>
</tr>
<tr class="even">
<td>Testovanie rovnosti podielov pre dve skupiny</td>
<td>Z-test</td>
<td>(Z _D N(0,1) )</td>
<td>(H_0): <span class="math inline">\(p_1 = p_2\)</span></td>
<td>mechanicky</td>
<td>(p) je odhad proporcie z oboch vzoriek naraz</td>
</tr>
<tr class="odd">
<td></td>
<td>Chí-Kvadrát test</td>
<td>(^2_1 )</td>
<td>(H_0): <span class="math inline">\(p_1 = p_2\)</span></td>
<td><code>prop.test()</code></td>
<td>Na základe kont. tabuľky.</td>
</tr>
<tr class="even">
<td>Asociácia medzi kategorickými premennými</td>
<td>Chí-Kvadrát test</td>
<td>(C = _i ^2_m )</td>
<td>(H_0): X a Y sú nezávislé</td>
<td><code>chisq.test()</code></td>
<td>(m = (c_1 - 1)(c_2-1))</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="cvičenia" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="cvičenia"><span class="header-section-number">8.9</span> Cvičenia</h2>
<!-- [R súbor k cvičeniam 4.Nov](https://www.dropbox.com/scl/fi/34lf7hxqdvo8uyvlf2qu9/20231123-labs07-base.R?rlkey=t4ge8keij03yn7qufc3qp74sv&dl=0) -->
<!-- [R súbor k cvičeniam 11.Nov](https://www.dropbox.com/scl/fi/5govia98jibfdf1ca9dxa/PAS2_Cvicenia_11Nov2024_base.R?rlkey=z78h68oqmdqiup6o67u3xp39k&dl=0) -->
<!-- [R súbor k cvičeniam 11.11.2022 riešenia](https://www.dropbox.com/s/k5y1851ekt7jpe8/labs_week8_solutions_package.zip?dl=0) -->
<!-- [R súbor k cvičeniam](https://www.dropbox.com/s/vqldvranyfat4ok/labs_week9.R?dl=0) -->
<!-- [R súbor k cvičeniam 18.11.2022 riešenia](https://www.dropbox.com/s/e9gqygq4c0ydp4e/labs_week9_solutions.R?dl=0) -->
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.1</strong></span> Využite dáta <code>EuStockMarkets</code> z knižnice <code>datasets</code> a porovnajte priemerné denné výnosy nemeckého DAX a britského FTSE. Využijete párový alebo nepárový test? Dáta zobrazte.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.2</strong></span> Z datasetu <code>USArrests</code> porovnajte úrovne rôznych zločinov podľa toho, či žije v mestách veľa ľudí. Dáta zobrazte.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.3</strong></span> V datasete <code>airquality</code> sú informácie o kvalite vzduchu. Otestujte jednostrannú hypotézu, či je rýchlosť vetra väčšia ako 11 míľ za hodinu. Podporte tento výsledok aj vizuálne. Porovnajte T-test so Z-testom.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.4</strong></span> Z datasetu <code>movies</code> z knižnice <code>ggplot2movies</code> otestuje hypotézu, že vo filmoch vydaných po roku 2000 (vrátane) sú komédie kratšie ako akčné filmy. Filmy vhodne zobrazte (napríklad ak je priveľa dát na zobrazenie všetkých filmov, môžete zobraziť aspoň náhodnú podvzorku).</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.5</strong></span> V datasete <code>energy</code> z knižnice <code>ISwR</code> je 24-hodinový energetický výdaj v MJ pre 22 pacientiek. Porovnajte a zobrazte energetický výdaj pre obézne a neobézne pacientky. Ešte predtým ako urobíte nejaký test dáta zobrazte. Aký výsledok očakávate? Je v tomto prípade test užitočný?</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.6</strong></span> V datasete <code>stroke</code> z knižnice <code>ISwR</code> sú informácie o 829 pacientoch z Tartu medzi 1991-1993, ktorí mali porážku. Porovnajte sumárne štatistiky medzi pacientami, ktorí umreli a ktorí prežili (v prípade kategorických premenných sa pozrite na proporcie). V ktorých premenných nachádzate signifikantné rozdiely? Hint: pomôžte si funkciou <code>st</code> z knižnice <code>vtable</code>. Vaše zistenia interpretujte.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.7</strong></span> Zreprodukujte obrázok zo simulácie konfidenčných intervalov. Nastavte <code>set.seed(29)</code>, zvoľte <span class="math inline">\(n=10\)</span> a generujte vzorky z rozdelenia <span class="math inline">\(N(2,1).\)</span></p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.8</strong></span> Mechanicky zreprodukujte konfidenčné intervaly z <a href="https://www.focus-research.sk/wp-content/uploads/2022/07/Volebne-preferencie-politickych-stran_jun-2022.pdf">tohoto prieskumu</a>.</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.9</strong></span> <a href="https://www.median.sk/pdf/OSTATNE/4521527_RTVS_Hodnotenievlady_v22.pdf">Tento prieskum</a> neobsahuje kvantifikáciu neistoty pomocou konfidenčných intervalov. Doplňte informáciu o konfidenčných intervaloch na slajd na strane 8 (prieskum volebných preferencií). Je rozdiel v proporcii hlasujúcich pre 2 strany, ktoré získali <span class="math inline">\(5\%\)</span> a <span class="math inline">\(4.7\%\)</span> štatisticky významný?</p>
</div>
<div id="exr-" class="Exercise theorem exercise">
<p><span class="theorem-title"><strong>Cvičenie 8.10</strong></span> Z knižnice <code>ISLR</code> máme v datasete <code>Wage</code> informácie o mzdách. Vytvorte kategorickú premennú, či je daná mzda nad alebo pod mediánom. Pozrite sa ako táto kategorická premenná suvisí so vzdelaním a s rasou.</p>
</div>
<!-- [R súbor z cvičení 23.11.2023](https://www.dropbox.com/scl/fi/ttr6hvp9nfs0g0ugsw2ub/20231123-labs07.R?rlkey=ih72oepnm4bbvznk1wlloy7u2&dl=0) -->
<p><a href="https://www.dropbox.com/scl/fi/clq4iydk8c1dh6utcyawy/cvicenie8-part1.R?rlkey=h5r4lt9y6igu2l2ldyoedfjp3&amp;dl=0">R súbor z cvičení 3.11.2025</a></p>
<!-- ## Domáca úloha 3 -->
<!-- Deadline je 4.12.2023 o 20:00. Váš kód aj ostatné pomocné súbory (napríklad dáta) mi zabaľte do jedného (1) zip súboru (nie `rar` súbor, nie OneDrive folder) v tvare `du3_MenoPriezvisko.zip` (napr. `du3_PeterKovac.zip`) a pošlite na email `miroslava.sartorisova@umb.sk`. Kód musí byť **spustiteľný** (vyskúšajte či Vám prebehne, keď máte prázdnu pamäť. Tú si uvoľníte pomocou príkazu `rm(list=ls())`) a podrobne okomentovaný. Odovzdávate mi Vašu **vlastnú** prácu (teda nie niekoho iného). -->
<!-- Dáta sú vymyslené, [stiahnete si ich tu](https://www.dropbox.com/scl/fi/1s1geleqi6ji9wv5odlpm/du3-data.R?rlkey=vvrpz87v5q2n296qqqtagz4jx&dl=0). -->
<!-- Všetky vaše zistenia podrobne okomentujte a podporte vhodným obrázkom. -->
<!-- ::: {.exercise name="DÚ 3.1 (teplota)"} -->
<!-- Máme údaje o teplote vzduchu na niekoľkých meracích staniciach z dňa 24.12.2021 a 24.12.2022. -->
<!-- Priemerná teplota za posledné roky v tento deň bola 1°C. -->
<!-- a) Zistite, či v roku 2021 bola teplota štatisticky významne iná ako za posledné roky. Ak áno, použitím vhodnej alternatívy zistite, či bola vyššia alebo nižšia. -->
<!-- b) Zistite, či v roku 2022 bola teplota štatisticky významne iná ako za posledné roky. Ak áno, použitím vhodnej alternatívy zistite, či bola vyššia alebo nižšia. -->
<!-- c) Použitím vhodného testu zistite, či sa teploty v roku 2021 a 2022 štatisticky významne líšia. Vysvetlite, prečo ste zvolili tento test. -->
<!-- d) Aký je konfidenčný interval pre priemernú teplotu v roku 2022? -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.2 (borovice)"} -->
<!-- Máme údaje o výške borovice lesnej na Slovensku a v Poľsku. Priemerná výška borovice je 30 metrov. -->
<!-- a) Zistite, či na Slovensku je výška borovíc štatisticky významne iná, ako priemer. Ak áno, použitím vhodného testu určite, či je vyššia alebo nižšia. -->
<!-- b) Zistite, či na Slovensku je výška borovíc štatisticky významne iná, ako priemer, na hladine významnosti $\alpha = 0.01$. Ak áno, použitím vhodného testu určite, či je vyššia alebo nižšia. -->
<!-- c) Zistite, či v Poľsku je výška borovíc štatisticky významne iná, ako priemer. Ak áno, použitím vhodného testu určite, či je vyššia alebo nižšia. -->
<!-- d) Zistite, či sú borovice na Slovensku štatisticky významne rovnako vysoké ako v Poľsku. Ak nie, použitím vhodnej alternatívy zistite, kde sú vyššie.  -->
<!-- e) Urobte konfidenčný interval pre priemernú výšku borovice na Slovensku. -->
<!-- f) Urobte konfidenčný interval pre priemernú výšku borovice na Slovensku pre $\alpha = 0.01$. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.3 (dopravný prostriedok)"} -->
<!-- V kontingenčných tabuľkách máte údaje o používaní dopravného prostriedku podľa pohlavia a podľa toho, či človek študuje, pracuje alebo je nezamestnaný. -->
<!-- a) Zistite, či výber dopravného prostriedku štatisticky významne závisí od pohlavia. -->
<!-- b) Zistite, či výber dopravného prostriedku štatisticky významne závisí od toho, či človek študuje, pracuje alebo je nezamestnaný. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.4 (BMI)"} -->
<!-- V kontingenčných tabuľkách máte údaje o BMI, pohlaví, počte rôznych športových aktivít (za týždeň). -->
<!-- a) Zistite, či je štatisticky významný rozdiel medzi BMI mužov a BMI žien. -->
<!-- b) Zistite, či celkový počet športových aktivít medzi mužmi a ženami sa štatisticky významne líši. -->
<!-- c) Rozdeľte BMI do 3 kategórií (nad, pod a norma). Pozrite sa, ako táto kategorická premenná suvisí s pohlavím a celkovým počtom športových aktivít za týždeň. -->
<!-- ::: -->
<!-- ## Domáca úloha 3 (dobrovoľná a nehodnotená) -->
<!-- Deadline je 24.11.2024 o 20:00. Váš kód aj ostatné pomocné súbory (napríklad dáta) mi zabaľte do jedného (1) zip súboru (nie `rar` súbor, nie OneDrive folder) v tvare `du2_MenoPriezvisko.zip` (napr. `du3_PeterKovac.zip`) a pošlite cez formulár, ktorého odkaz je na stránke. Kód musí byť spustiteľný a podrobne okomentovaný. Odovzdávate mi Vašu **vlastnú** prácu. Domáca úloha je **dobrovoľná** a **nehodnotená**. V prípade, že ju pošlete do termínu dostanete spätnú väzbu -->
<!-- ::: {.exercise name="DÚ 3.1 (test rovnosti stredných hodnôt)"} -->
<!-- Uvažuje dve vzorky $1,2,3,1,1,2,3,4,1,1,1$ a $2,3,2,1,1,1,2,3,4,3,2,1,2,4,3,6,4$. Zobrazte dáta a otestuje rovnosť stredných hodnôt na hladine významnosti $95\%$. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.2 (zrak)"} -->
<!-- V datasete `eyegrade` v knižnici `faraway` sú informácie o kvalite zraku u 16 pacientov. Otestujte hypotézu, že kvalita pravého oka je nezávislá od kvality ľavého oka. Dáta vhodne zobrazte. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.3 (sťažnosti, mzda, objem práce)"} -->
<!-- V datasete `esdcomp` v knižnici `faraway` sú informácie o sťažnostiach pacientov na lekárov/ky. Porovnajte počet sťažností, hodinovú mzdu a počet odrobených hodín pre mužov a ženy a potom lekárov/iek v zácviku voči tým, ktorí nie sú v zácviku (premenná `residency`), teda dokopy 6 porovnaní. Zvoľte vhodný test aj vizualizáciu. -->
<!-- ::: -->
<!-- <!-- ::: {.exercise name="DÚ 3.4 (prijímačky na Berkeley)"} -->
<!-- <!-- V datasete `UCBAdmissions` v knižnici `datasets` sú informácie o prijímacom konaní na Berkeley v roku 1973 na 6 rôznych departmentoch. -->
<!-- <!-- Otázkou môže byť, či nedochádzalo k diskriminácii. Otestujte či boli rovnako prijímané ženy a muži na jedntlivých departmentoch. -->
<!-- <!-- Potom otestuje či boli rovnako prijímané ženy a muži **celkovo**. -->
<!-- <!-- Výsledky interpretujte a vysvetlite. -->
<!-- <!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.4"} -->
<!-- Pripravte si funkciu, ktorá Vám bude uľahčovať život. Jej vstupom budú dva vektory $x$ a $y$, ktorých stredné hodnoty (alebo proporcie) budete chcieť porovnať a iné potenciálne užitočné vstupy. Výsledkom funkcie bude vhodné a vyladené (vhodný výber farieb, popisov, legendy a iných grafických elementov) grafické porovnanie s informáciou o použitom teste a p-hodnotou. Demonštrujte túto Vami vytvorenú funkciu na DÚ 3.1 a 3.3. -->
<!-- ::: -->
<!-- ::: {.exercise name="DÚ 3.5 (BONUS)"} -->
<!-- V datasete `heart.rate` z knižnice `ISwR` je odmeraný pulz pre 9 pacientov v rôzych časoch po podaní lieku enalaprilat. Pozrite sa na rozdiel pred podaním lieku a pulz odmeraný v rôznych časoch. Otestujte tieto rozdiely vhodnými testami (0 vs 30, 30 vs 60, 60 vs 120). Zobrazte vedľa seba 4 boxploty pre pulz v rôznych časoch. -->
<!-- ::: -->
</section>
<section id="domáca-úloha-3" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="domáca-úloha-3"><span class="header-section-number">8.10</span> Domáca úloha 3</h2>
<p>Prosím odovzdať do 9.11.2025 19:59 cez formulár (tento Vám príde emailom).</p>
<p>V riešeniach používajte prosím plnovýznamové vety a nahrávajte riešenia v jednom pdf súbore nazvanom podľa Vašich priezvísk v tvare DU3_priezvisko1_priezvisko2.pdf (napríklad DU3_Kovacova_Zelinka.pdf).</p>
<p>V úlohách 1-3 máme dané datasety, úlohy vhodne vizualizujte, opíšte prečo ste použili dané atribúty, paremetre, typ grafu a následne opíšte čo na danom grafe môžeme vidieť.</p>
<p>V úlohách 4-7 robíme t-testy, z-testy a overanie hypotéz.</p>
<div class="exercise" name="DÚ 3.1, mtcars">
<p>Použite dataset mtcars (základný v R).</p>
<ol type="1">
<li><p>Ktoré autá majú najväčšiu variabilitu v spotrebe na diaľnici?</p></li>
<li><p>Rastie spotreba v meste s objemom motora?</p></li>
<li><p>Koľko áut má pohon 4x4?</p></li>
<li><p>Ako vyzerá rozdelenie spotreby v meste?</p></li>
<li><p>Majú autá s 8 valcami inú spotrebu ako ostatné?</p></li>
</ol>
</div>
<div class="exercise" name="DÚ 3.2, diamonds">
<p>Použite dataset diamonds (základný v R).</p>
<ol type="1">
<li><p>Ktorý rez má najviac odľahlích cien?</p></li>
<li><p>Rastie cena s váhou?</p></li>
<li><p>Koľko briliantov má farbu “D” (najlepšia)?</p></li>
<li><p>Ako vyzerá rozdelenie váhy?</p></li>
<li><p>Majú brilianty s rezom “Ideal” inú cenu ako “Fair”?</p></li>
</ol>
</div>
<div class="exercise" name="DÚ 3.3, economics">
<p>Použite dataset economics (základný v R).</p>
<ol type="1">
<li><p>Ako sa vyvíjala nezamestnanosť v čase?</p></li>
<li><p>Rástla populácia rovnomerne?</p></li>
<li><p>Aký je vzťah medzi nezamestnanosťou a úsporami?</p></li>
<li><p>Kedy bola najvyššia nezamestnanosť?</p></li>
<li><p>Ako sa menila miera úspor v čase?</p></li>
</ol>
</div>
<div class="exercise" name="DÚ 3.4, mtcars2">
<p>Použite dataset mtcars (základný v R). Porovnajte priemernú spotrebu paliva medzi autami s automatickou a manuálnou prevodovkou.</p>
<ol type="1">
<li><p>Použite T-test a Z-test (predpokladajte, že poznáte σ ako SD celej vzorky). Odôvodnite prečo párový alebo nepárový.</p></li>
<li><p>Určte, či existuje signifikantný rozdiel v spotrebe medzi typmi prevodovky.</p></li>
<li><p>Vizualizujte výsledky (napr. boxplot).</p></li>
</ol>
<p>Bonus: Skúste jednostrannú hypotézu: “autá s manuálnou prevodovkou majú vyššiu spotrebu než automaty” a porovnajte s opačnou hypotézou. Výsledok opíšte.</p>
</div>
<div class="exercise" name="DÚ 3.5, aiquality">
<p>Použite dataset airquality (základný v R). Otestujte jednostrannú hypotézu, či je teplota (Temp) väčšia ako 80°F počas leta.</p>
<ol type="1">
<li><p>Otestujte danú hypotézu (či je teplota väčšia ako 80°F počas leta).</p></li>
<li><p>Vizualizujte histogram s čiarou pre hodnotu 80°F.</p></li>
<li><p>Skúste aj opačnú hypotézu (Temp &lt; 80°F) a porovnajte výsledky.</p></li>
</ol>
</div>
<div class="exercise" name="DÚ 3.6, sleep">
<p>Použite dataset sleep (základný v R). Dataset sleep obsahuje záznamy o spánku 10 osôb po dvoch typoch liekov (group = 1 a group = 2). Otestujte, či existuje signifikantný rozdiel v spánku medzi týmito dvoma liekmi.</p>
<ol type="1">
<li><p>Rozhodnite, či je test párový alebo nepárový a prečo.</p></li>
<li><p>Vizualizujte rozdiel (napr. boxplot).</p></li>
<li><p>Vykonajte aj jednostrannú hypotézu: “liek 2 zvyšuje spánok oproti lieku 1”.</p></li>
</ol>
<p>Tip: Môžete použiť pivot_wider na samostatné vektory pre T-test:</p>
<p>Môžete použiť pivot_longer na jednoduchšiu vizualizáciu s boxplotom:</p>
</div>


</section>
</section></main></div>


 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Skopírované!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Skopírované!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./visual.html" class="pagination-link" aria-label="Zobrazovanie dát">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Zobrazovanie dát</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./reg.html" class="pagination-link" aria-label="Úvod do lineárnej regresie">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Úvod do lineárnej regresie</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
 <!-- /content -->




</body></html>